// Generated by svd2swift.

import MMIO

/// Access control lists
@RegisterBlock
struct ACL {
    /// Unspecified
    @RegisterBlock(offset: 0x800, stride: 0x10, count: 8)
    var acl: RegisterArray<ACL>
}

extension ACL {
    /// Unspecified
    @RegisterBlock
    struct ACL {
        /// Description cluster: Start address of region to protect. The start address must be word-aligned.
        @RegisterBlock(offset: 0x0)
        var addr: Register<ADDR>

        /// Description cluster: Size of region to protect counting from address ACL[n].ADDR. Writing a '0' has no effect.
        @RegisterBlock(offset: 0x4)
        var size: Register<SIZE>

        /// Description cluster: Access permissions for region n as defined by start address ACL[n].ADDR and size ACL[n].SIZE
        @RegisterBlock(offset: 0x8)
        var perm: Register<PERM>
    }
}

extension ACL.ACL {
    /// Description cluster: Start address of region to protect. The start address must be word-aligned.
    @Register(bitWidth: 32)
    struct ADDR {
        /// Start address of flash region n. The start address must point to a flash page boundary.
        @ReadWrite(bits: 0..<32)
        var addr_field: ADDR_FIELD
    }

    /// Description cluster: Size of region to protect counting from address ACL[n].ADDR. Writing a '0' has no effect.
    @Register(bitWidth: 32)
    struct SIZE {
        /// Size of flash region n in bytes. Must be a multiple of the flash page size.
        @ReadWrite(bits: 0..<32)
        var size_field: SIZE_FIELD
    }

    /// Description cluster: Access permissions for region n as defined by start address ACL[n].ADDR and size ACL[n].SIZE
    @Register(bitWidth: 32)
    struct PERM {
        /// Configure write and erase permissions for region n. Writing a '0' has no effect.
        @ReadWrite(bits: 1..<2, as: WRITEValues.self)
        var write: WRITE

        /// Configure read permissions for region n. Writing a '0' has no effect.
        @ReadWrite(bits: 2..<3, as: READValues.self)
        var read: READ
    }
}

extension ACL.ACL.PERM {
    struct WRITEValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Allow write and erase instructions to region n.
        static let Enable = Self(rawValue: 0x0)

        /// Block write and erase instructions to region n.
        static let Disable = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension ACL.ACL.PERM {
    struct READValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Allow read instructions to region n.
        static let Enable = Self(rawValue: 0x0)

        /// Block read instructions to region n.
        static let Disable = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
