// Generated by svd2swift.

import MMIO

/// Accelerated Address Resolver
let aar = AAR(unsafeAddress: 0x4000f000)

/// Access control lists
let acl = ACL(unsafeAddress: 0x4001e000)

/// Access Port Protection
let approtect = APPROTECT(unsafeAddress: 0x40000000)

/// AES CCM mode encryption
let ccm = CCM(unsafeAddress: 0x4000f000)

/// Clock control
let clock = CLOCK(unsafeAddress: 0x40000000)

/// Comparator
let comp = COMP(unsafeAddress: 0x40013000)

/// AES ECB Mode Encryption
let ecb = ECB(unsafeAddress: 0x4000e000)

/// Event generator unit 0
let egu0 = EGU0(unsafeAddress: 0x40014000)

/// Event generator unit 1
let egu1 = EGU1(unsafeAddress: 0x40015000)

/// Event generator unit 2
let egu2 = EGU2(unsafeAddress: 0x40016000)

/// Event generator unit 3
let egu3 = EGU3(unsafeAddress: 0x40017000)

/// Event generator unit 4
let egu4 = EGU4(unsafeAddress: 0x40018000)

/// Event generator unit 5
let egu5 = EGU5(unsafeAddress: 0x40019000)

/// Factory information configuration registers
let ficr = FICR(unsafeAddress: 0x10000000)

/// FPU
let fpu = FPU(unsafeAddress: 0x40026000)

/// GPIO Tasks and Events
let gpiote = GPIOTE(unsafeAddress: 0x40006000)

/// Inter-IC Sound
let i2s = I2S(unsafeAddress: 0x40025000)

/// Low-power comparator
let lpcomp = LPCOMP(unsafeAddress: 0x40013000)

/// Memory Watch Unit
let mwu = MWU(unsafeAddress: 0x40020000)

/// NFC-A compatible radio
let nfct = NFCT(unsafeAddress: 0x40005000)

/// Non Volatile Memory Controller
let nvmc = NVMC(unsafeAddress: 0x4001e000)

/// GPIO Port 1
let p0 = P0(unsafeAddress: 0x50000000)

/// GPIO Port 2
let p1 = P1(unsafeAddress: 0x50000300)

/// Pulse Density Modulation (Digital Microphone) Interface
let pdm = PDM(unsafeAddress: 0x4001d000)

/// Power control
let power = POWER(unsafeAddress: 0x40000000)

/// Programmable Peripheral Interconnect
let ppi = PPI(unsafeAddress: 0x4001f000)

/// Pulse width modulation unit 0
let pwm0 = PWM0(unsafeAddress: 0x4001c000)

/// Pulse width modulation unit 1
let pwm1 = PWM1(unsafeAddress: 0x40021000)

/// Pulse width modulation unit 2
let pwm2 = PWM2(unsafeAddress: 0x40022000)

/// Pulse width modulation unit 3
let pwm3 = PWM3(unsafeAddress: 0x4002d000)

/// Quadrature Decoder
let qdec = QDEC(unsafeAddress: 0x40012000)

/// 2.4 GHz radio
let radio = RADIO(unsafeAddress: 0x40001000)

/// Random Number Generator
let rng = RNG(unsafeAddress: 0x4000d000)

/// Real time counter 0
let rtc0 = RTC0(unsafeAddress: 0x4000b000)

/// Real time counter 1
let rtc1 = RTC1(unsafeAddress: 0x40011000)

/// Real time counter 2
let rtc2 = RTC2(unsafeAddress: 0x40024000)

/// Successive approximation register (SAR) analog-to-digital converter
let saadc = SAADC(unsafeAddress: 0x40007000)

/// Serial Peripheral Interface 0
let spi0 = SPI0(unsafeAddress: 0x40003000)

/// Serial Peripheral Interface 1
let spi1 = SPI1(unsafeAddress: 0x40004000)

/// Serial Peripheral Interface 2
let spi2 = SPI2(unsafeAddress: 0x40023000)

/// Serial Peripheral Interface Master with EasyDMA 0
let spim0 = SPIM0(unsafeAddress: 0x40003000)

/// Serial Peripheral Interface Master with EasyDMA 1
let spim1 = SPIM1(unsafeAddress: 0x40004000)

/// Serial Peripheral Interface Master with EasyDMA 2
let spim2 = SPIM2(unsafeAddress: 0x40023000)

/// Serial Peripheral Interface Master with EasyDMA 3
let spim3 = SPIM3(unsafeAddress: 0x4002f000)

/// SPI Slave 0
let spis0 = SPIS0(unsafeAddress: 0x40003000)

/// SPI Slave 1
let spis1 = SPIS1(unsafeAddress: 0x40004000)

/// SPI Slave 2
let spis2 = SPIS2(unsafeAddress: 0x40023000)

/// Software interrupt 0
let swi0 = SWI0(unsafeAddress: 0x40014000)

/// Software interrupt 1
let swi1 = SWI1(unsafeAddress: 0x40015000)

/// Software interrupt 2
let swi2 = SWI2(unsafeAddress: 0x40016000)

/// Software interrupt 3
let swi3 = SWI3(unsafeAddress: 0x40017000)

/// Software interrupt 4
let swi4 = SWI4(unsafeAddress: 0x40018000)

/// Software interrupt 5
let swi5 = SWI5(unsafeAddress: 0x40019000)

/// Temperature Sensor
let temp = TEMP(unsafeAddress: 0x4000c000)

/// Timer/Counter 0
let timer0 = TIMER0(unsafeAddress: 0x40008000)

/// Timer/Counter 1
let timer1 = TIMER1(unsafeAddress: 0x40009000)

/// Timer/Counter 2
let timer2 = TIMER2(unsafeAddress: 0x4000a000)

/// Timer/Counter 3
let timer3 = TIMER3(unsafeAddress: 0x4001a000)

/// Timer/Counter 4
let timer4 = TIMER4(unsafeAddress: 0x4001b000)

/// I2C compatible Two-Wire Interface 0
let twi0 = TWI0(unsafeAddress: 0x40003000)

/// I2C compatible Two-Wire Interface 1
let twi1 = TWI1(unsafeAddress: 0x40004000)

/// I2C compatible Two-Wire Master Interface with EasyDMA 0
let twim0 = TWIM0(unsafeAddress: 0x40003000)

/// I2C compatible Two-Wire Master Interface with EasyDMA 1
let twim1 = TWIM1(unsafeAddress: 0x40004000)

/// I2C compatible Two-Wire Slave Interface with EasyDMA 0
let twis0 = TWIS0(unsafeAddress: 0x40003000)

/// I2C compatible Two-Wire Slave Interface with EasyDMA 1
let twis1 = TWIS1(unsafeAddress: 0x40004000)

/// Universal Asynchronous Receiver/Transmitter
let uart0 = UART0(unsafeAddress: 0x40002000)

/// UART with EasyDMA 0
let uarte0 = UARTE0(unsafeAddress: 0x40002000)

/// UART with EasyDMA 1
let uarte1 = UARTE1(unsafeAddress: 0x40028000)

/// User information configuration registers
let uicr = UICR(unsafeAddress: 0x10001000)

/// Universal serial bus device
let usbd = USBD(unsafeAddress: 0x40027000)

/// Watchdog Timer
let wdt = WDT(unsafeAddress: 0x40010000)
