// Generated by svd2swift.

import MMIO

/// AES ECB Mode Encryption
@RegisterBlock
struct ECB {
    /// Start ECB block encrypt
    @RegisterBlock(offset: 0x0)
    var tasks_startecb: Register<TASKS_STARTECB>

    /// Abort a possible executing ECB operation
    @RegisterBlock(offset: 0x4)
    var tasks_stopecb: Register<TASKS_STOPECB>

    /// ECB block encrypt complete
    @RegisterBlock(offset: 0x100)
    var events_endecb: Register<EVENTS_ENDECB>

    /// ECB block encrypt aborted because of a STOPECB task or due to an error
    @RegisterBlock(offset: 0x104)
    var events_errorecb: Register<EVENTS_ERRORECB>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// ECB block encrypt memory pointers
    @RegisterBlock(offset: 0x504)
    var ecbdataptr: Register<ECBDATAPTR>
}

extension ECB {
    /// Start ECB block encrypt
    @Register(bitWidth: 32)
    struct TASKS_STARTECB {
        /// Start ECB block encrypt
        @WriteOnly(bits: 0..<1, as: TASKS_STARTECB_FIELDValues.self)
        var tasks_startecb_field: TASKS_STARTECB_FIELD
    }

    /// Abort a possible executing ECB operation
    @Register(bitWidth: 32)
    struct TASKS_STOPECB {
        /// Abort a possible executing ECB operation
        @WriteOnly(bits: 0..<1, as: TASKS_STOPECB_FIELDValues.self)
        var tasks_stopecb_field: TASKS_STOPECB_FIELD
    }

    /// ECB block encrypt complete
    @Register(bitWidth: 32)
    struct EVENTS_ENDECB {
        /// ECB block encrypt complete
        @ReadWrite(bits: 0..<1, as: EVENTS_ENDECB_FIELDValues.self)
        var events_endecb_field: EVENTS_ENDECB_FIELD
    }

    /// ECB block encrypt aborted because of a STOPECB task or due to an error
    @Register(bitWidth: 32)
    struct EVENTS_ERRORECB {
        /// ECB block encrypt aborted because of a STOPECB task or due to an error
        @ReadWrite(bits: 0..<1, as: EVENTS_ERRORECB_FIELDValues.self)
        var events_errorecb_field: EVENTS_ERRORECB_FIELD
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event ENDECB
        @ReadWrite(bits: 0..<1)
        var endecb: ENDECB

        /// Write '1' to enable interrupt for event ERRORECB
        @ReadWrite(bits: 1..<2)
        var errorecb: ERRORECB
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event ENDECB
        @ReadWrite(bits: 0..<1)
        var endecb: ENDECB

        /// Write '1' to disable interrupt for event ERRORECB
        @ReadWrite(bits: 1..<2)
        var errorecb: ERRORECB
    }

    /// ECB block encrypt memory pointers
    @Register(bitWidth: 32)
    struct ECBDATAPTR {
        /// Pointer to the ECB data structure (see Table 1 ECB data structure overview)
        @ReadWrite(bits: 0..<32)
        var ecbdataptr_field: ECBDATAPTR_FIELD
    }
}

extension ECB.TASKS_STARTECB {
    struct TASKS_STARTECB_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension ECB.TASKS_STOPECB {
    struct TASKS_STOPECB_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension ECB.EVENTS_ENDECB {
    struct EVENTS_ENDECB_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension ECB.EVENTS_ERRORECB {
    struct EVENTS_ERRORECB_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
