// Generated by svd2swift.

import MMIO

/// Event generator unit 0
@RegisterBlock
struct EGU0 {
    /// Description collection: Trigger n for triggering the corresponding TRIGGERED[n] event
    @RegisterBlock(offset: 0x0, stride: 0x4, count: 16)
    var tasks_trigger: RegisterArray<TASKS_TRIGGER>

    /// Description collection: Event number n generated by triggering the corresponding TRIGGER[n] task
    @RegisterBlock(offset: 0x100, stride: 0x4, count: 16)
    var events_triggered: RegisterArray<EVENTS_TRIGGERED>

    /// Enable or disable interrupt
    @RegisterBlock(offset: 0x300)
    var inten: Register<INTEN>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>
}

extension EGU0 {
    /// Description collection: Trigger n for triggering the corresponding TRIGGERED[n] event
    @Register(bitWidth: 32)
    struct TASKS_TRIGGER {
        /// Trigger n for triggering the corresponding TRIGGERED[n] event
        @WriteOnly(bits: 0..<1, as: TASKS_TRIGGER_FIELDValues.self)
        var tasks_trigger_field: TASKS_TRIGGER_FIELD
    }

    /// Description collection: Event number n generated by triggering the corresponding TRIGGER[n] task
    @Register(bitWidth: 32)
    struct EVENTS_TRIGGERED {
        /// Event number n generated by triggering the corresponding TRIGGER[n] task
        @ReadWrite(bits: 0..<1, as: EVENTS_TRIGGERED_FIELDValues.self)
        var events_triggered_field: EVENTS_TRIGGERED_FIELD
    }

    /// Enable or disable interrupt
    @Register(bitWidth: 32)
    struct INTEN {
        /// Enable or disable interrupt for event TRIGGERED[0]
        @ReadWrite(bits: 0..<1, as: TRIGGERED0Values.self)
        var triggered0: TRIGGERED0

        /// Enable or disable interrupt for event TRIGGERED[1]
        @ReadWrite(bits: 1..<2, as: TRIGGERED1Values.self)
        var triggered1: TRIGGERED1

        /// Enable or disable interrupt for event TRIGGERED[2]
        @ReadWrite(bits: 2..<3, as: TRIGGERED2Values.self)
        var triggered2: TRIGGERED2

        /// Enable or disable interrupt for event TRIGGERED[3]
        @ReadWrite(bits: 3..<4, as: TRIGGERED3Values.self)
        var triggered3: TRIGGERED3

        /// Enable or disable interrupt for event TRIGGERED[4]
        @ReadWrite(bits: 4..<5, as: TRIGGERED4Values.self)
        var triggered4: TRIGGERED4

        /// Enable or disable interrupt for event TRIGGERED[5]
        @ReadWrite(bits: 5..<6, as: TRIGGERED5Values.self)
        var triggered5: TRIGGERED5

        /// Enable or disable interrupt for event TRIGGERED[6]
        @ReadWrite(bits: 6..<7, as: TRIGGERED6Values.self)
        var triggered6: TRIGGERED6

        /// Enable or disable interrupt for event TRIGGERED[7]
        @ReadWrite(bits: 7..<8, as: TRIGGERED7Values.self)
        var triggered7: TRIGGERED7

        /// Enable or disable interrupt for event TRIGGERED[8]
        @ReadWrite(bits: 8..<9, as: TRIGGERED8Values.self)
        var triggered8: TRIGGERED8

        /// Enable or disable interrupt for event TRIGGERED[9]
        @ReadWrite(bits: 9..<10, as: TRIGGERED9Values.self)
        var triggered9: TRIGGERED9

        /// Enable or disable interrupt for event TRIGGERED[10]
        @ReadWrite(bits: 10..<11, as: TRIGGERED10Values.self)
        var triggered10: TRIGGERED10

        /// Enable or disable interrupt for event TRIGGERED[11]
        @ReadWrite(bits: 11..<12, as: TRIGGERED11Values.self)
        var triggered11: TRIGGERED11

        /// Enable or disable interrupt for event TRIGGERED[12]
        @ReadWrite(bits: 12..<13, as: TRIGGERED12Values.self)
        var triggered12: TRIGGERED12

        /// Enable or disable interrupt for event TRIGGERED[13]
        @ReadWrite(bits: 13..<14, as: TRIGGERED13Values.self)
        var triggered13: TRIGGERED13

        /// Enable or disable interrupt for event TRIGGERED[14]
        @ReadWrite(bits: 14..<15, as: TRIGGERED14Values.self)
        var triggered14: TRIGGERED14

        /// Enable or disable interrupt for event TRIGGERED[15]
        @ReadWrite(bits: 15..<16, as: TRIGGERED15Values.self)
        var triggered15: TRIGGERED15
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event TRIGGERED[0]
        @ReadWrite(bits: 0..<1)
        var triggered0: TRIGGERED0

        /// Write '1' to enable interrupt for event TRIGGERED[1]
        @ReadWrite(bits: 1..<2)
        var triggered1: TRIGGERED1

        /// Write '1' to enable interrupt for event TRIGGERED[2]
        @ReadWrite(bits: 2..<3)
        var triggered2: TRIGGERED2

        /// Write '1' to enable interrupt for event TRIGGERED[3]
        @ReadWrite(bits: 3..<4)
        var triggered3: TRIGGERED3

        /// Write '1' to enable interrupt for event TRIGGERED[4]
        @ReadWrite(bits: 4..<5)
        var triggered4: TRIGGERED4

        /// Write '1' to enable interrupt for event TRIGGERED[5]
        @ReadWrite(bits: 5..<6)
        var triggered5: TRIGGERED5

        /// Write '1' to enable interrupt for event TRIGGERED[6]
        @ReadWrite(bits: 6..<7)
        var triggered6: TRIGGERED6

        /// Write '1' to enable interrupt for event TRIGGERED[7]
        @ReadWrite(bits: 7..<8)
        var triggered7: TRIGGERED7

        /// Write '1' to enable interrupt for event TRIGGERED[8]
        @ReadWrite(bits: 8..<9)
        var triggered8: TRIGGERED8

        /// Write '1' to enable interrupt for event TRIGGERED[9]
        @ReadWrite(bits: 9..<10)
        var triggered9: TRIGGERED9

        /// Write '1' to enable interrupt for event TRIGGERED[10]
        @ReadWrite(bits: 10..<11)
        var triggered10: TRIGGERED10

        /// Write '1' to enable interrupt for event TRIGGERED[11]
        @ReadWrite(bits: 11..<12)
        var triggered11: TRIGGERED11

        /// Write '1' to enable interrupt for event TRIGGERED[12]
        @ReadWrite(bits: 12..<13)
        var triggered12: TRIGGERED12

        /// Write '1' to enable interrupt for event TRIGGERED[13]
        @ReadWrite(bits: 13..<14)
        var triggered13: TRIGGERED13

        /// Write '1' to enable interrupt for event TRIGGERED[14]
        @ReadWrite(bits: 14..<15)
        var triggered14: TRIGGERED14

        /// Write '1' to enable interrupt for event TRIGGERED[15]
        @ReadWrite(bits: 15..<16)
        var triggered15: TRIGGERED15
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event TRIGGERED[0]
        @ReadWrite(bits: 0..<1)
        var triggered0: TRIGGERED0

        /// Write '1' to disable interrupt for event TRIGGERED[1]
        @ReadWrite(bits: 1..<2)
        var triggered1: TRIGGERED1

        /// Write '1' to disable interrupt for event TRIGGERED[2]
        @ReadWrite(bits: 2..<3)
        var triggered2: TRIGGERED2

        /// Write '1' to disable interrupt for event TRIGGERED[3]
        @ReadWrite(bits: 3..<4)
        var triggered3: TRIGGERED3

        /// Write '1' to disable interrupt for event TRIGGERED[4]
        @ReadWrite(bits: 4..<5)
        var triggered4: TRIGGERED4

        /// Write '1' to disable interrupt for event TRIGGERED[5]
        @ReadWrite(bits: 5..<6)
        var triggered5: TRIGGERED5

        /// Write '1' to disable interrupt for event TRIGGERED[6]
        @ReadWrite(bits: 6..<7)
        var triggered6: TRIGGERED6

        /// Write '1' to disable interrupt for event TRIGGERED[7]
        @ReadWrite(bits: 7..<8)
        var triggered7: TRIGGERED7

        /// Write '1' to disable interrupt for event TRIGGERED[8]
        @ReadWrite(bits: 8..<9)
        var triggered8: TRIGGERED8

        /// Write '1' to disable interrupt for event TRIGGERED[9]
        @ReadWrite(bits: 9..<10)
        var triggered9: TRIGGERED9

        /// Write '1' to disable interrupt for event TRIGGERED[10]
        @ReadWrite(bits: 10..<11)
        var triggered10: TRIGGERED10

        /// Write '1' to disable interrupt for event TRIGGERED[11]
        @ReadWrite(bits: 11..<12)
        var triggered11: TRIGGERED11

        /// Write '1' to disable interrupt for event TRIGGERED[12]
        @ReadWrite(bits: 12..<13)
        var triggered12: TRIGGERED12

        /// Write '1' to disable interrupt for event TRIGGERED[13]
        @ReadWrite(bits: 13..<14)
        var triggered13: TRIGGERED13

        /// Write '1' to disable interrupt for event TRIGGERED[14]
        @ReadWrite(bits: 14..<15)
        var triggered14: TRIGGERED14

        /// Write '1' to disable interrupt for event TRIGGERED[15]
        @ReadWrite(bits: 15..<16)
        var triggered15: TRIGGERED15
    }
}

extension EGU0.TASKS_TRIGGER {
    struct TASKS_TRIGGER_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.EVENTS_TRIGGERED {
    struct EVENTS_TRIGGERED_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED4Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED5Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED6Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED7Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED8Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED9Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED10Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED11Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED12Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED13Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED14Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension EGU0.INTEN {
    struct TRIGGERED15Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
