// Generated by svd2swift.

import MMIO

/// FPU
@RegisterBlock
struct FPU {
    /// Unused.
    @RegisterBlock(offset: 0x0)
    var unused: Register<UNUSED>
}

extension FPU {
    /// Unused.
    @Register(bitWidth: 32)
    struct UNUSED {
    }
}
