// Generated by svd2swift.

import MMIO

/// Power control
@RegisterBlock
struct POWER {
    /// Enable Constant Latency mode
    @RegisterBlock(offset: 0x78)
    var tasks_constlat: Register<TASKS_CONSTLAT>

    /// Enable Low-power mode (variable latency)
    @RegisterBlock(offset: 0x7c)
    var tasks_lowpwr: Register<TASKS_LOWPWR>

    /// Power failure warning
    @RegisterBlock(offset: 0x108)
    var events_pofwarn: Register<EVENTS_POFWARN>

    /// CPU entered WFI/WFE sleep
    @RegisterBlock(offset: 0x114)
    var events_sleepenter: Register<EVENTS_SLEEPENTER>

    /// CPU exited WFI/WFE sleep
    @RegisterBlock(offset: 0x118)
    var events_sleepexit: Register<EVENTS_SLEEPEXIT>

    /// Voltage supply detected on VBUS
    @RegisterBlock(offset: 0x11c)
    var events_usbdetected: Register<EVENTS_USBDETECTED>

    /// Voltage supply removed from VBUS
    @RegisterBlock(offset: 0x120)
    var events_usbremoved: Register<EVENTS_USBREMOVED>

    /// USB 3.3 V supply ready
    @RegisterBlock(offset: 0x124)
    var events_usbpwrrdy: Register<EVENTS_USBPWRRDY>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// Reset reason
    @RegisterBlock(offset: 0x400)
    var resetreas: Register<RESETREAS>

    /// Deprecated register - RAM status register
    @RegisterBlock(offset: 0x428)
    var ramstatus: Register<RAMSTATUS>

    /// USB supply status
    @RegisterBlock(offset: 0x438)
    var usbregstatus: Register<USBREGSTATUS>

    /// System OFF register
    @RegisterBlock(offset: 0x500)
    var systemoff: Register<SYSTEMOFF>

    /// Power-fail comparator configuration
    @RegisterBlock(offset: 0x510)
    var pofcon: Register<POFCON>

    /// General purpose retention register
    @RegisterBlock(offset: 0x51c)
    var gpregret: Register<GPREGRET>

    /// General purpose retention register
    @RegisterBlock(offset: 0x520)
    var gpregret2: Register<GPREGRET2>

    /// Enable DC/DC converter for REG1 stage
    @RegisterBlock(offset: 0x578)
    var dcdcen: Register<DCDCEN>

    /// Main supply status
    @RegisterBlock(offset: 0x640)
    var mainregstatus: Register<MAINREGSTATUS>

    /// Unspecified
    @RegisterBlock(offset: 0x900, stride: 0x10, count: 9)
    var ram: RegisterArray<RAM>
}

extension POWER {
    /// Enable Constant Latency mode
    @Register(bitWidth: 32)
    struct TASKS_CONSTLAT {
        /// Enable Constant Latency mode
        @WriteOnly(bits: 0..<1, as: TASKS_CONSTLAT_FIELDValues.self)
        var tasks_constlat_field: TASKS_CONSTLAT_FIELD
    }

    /// Enable Low-power mode (variable latency)
    @Register(bitWidth: 32)
    struct TASKS_LOWPWR {
        /// Enable Low-power mode (variable latency)
        @WriteOnly(bits: 0..<1, as: TASKS_LOWPWR_FIELDValues.self)
        var tasks_lowpwr_field: TASKS_LOWPWR_FIELD
    }

    /// Power failure warning
    @Register(bitWidth: 32)
    struct EVENTS_POFWARN {
        /// Power failure warning
        @ReadWrite(bits: 0..<1, as: EVENTS_POFWARN_FIELDValues.self)
        var events_pofwarn_field: EVENTS_POFWARN_FIELD
    }

    /// CPU entered WFI/WFE sleep
    @Register(bitWidth: 32)
    struct EVENTS_SLEEPENTER {
        /// CPU entered WFI/WFE sleep
        @ReadWrite(bits: 0..<1, as: EVENTS_SLEEPENTER_FIELDValues.self)
        var events_sleepenter_field: EVENTS_SLEEPENTER_FIELD
    }

    /// CPU exited WFI/WFE sleep
    @Register(bitWidth: 32)
    struct EVENTS_SLEEPEXIT {
        /// CPU exited WFI/WFE sleep
        @ReadWrite(bits: 0..<1, as: EVENTS_SLEEPEXIT_FIELDValues.self)
        var events_sleepexit_field: EVENTS_SLEEPEXIT_FIELD
    }

    /// Voltage supply detected on VBUS
    @Register(bitWidth: 32)
    struct EVENTS_USBDETECTED {
        /// Voltage supply detected on VBUS
        @ReadWrite(bits: 0..<1, as: EVENTS_USBDETECTED_FIELDValues.self)
        var events_usbdetected_field: EVENTS_USBDETECTED_FIELD
    }

    /// Voltage supply removed from VBUS
    @Register(bitWidth: 32)
    struct EVENTS_USBREMOVED {
        /// Voltage supply removed from VBUS
        @ReadWrite(bits: 0..<1, as: EVENTS_USBREMOVED_FIELDValues.self)
        var events_usbremoved_field: EVENTS_USBREMOVED_FIELD
    }

    /// USB 3.3 V supply ready
    @Register(bitWidth: 32)
    struct EVENTS_USBPWRRDY {
        /// USB 3.3 V supply ready
        @ReadWrite(bits: 0..<1, as: EVENTS_USBPWRRDY_FIELDValues.self)
        var events_usbpwrrdy_field: EVENTS_USBPWRRDY_FIELD
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event POFWARN
        @ReadWrite(bits: 2..<3)
        var pofwarn: POFWARN

        /// Write '1' to enable interrupt for event SLEEPENTER
        @ReadWrite(bits: 5..<6)
        var sleepenter: SLEEPENTER

        /// Write '1' to enable interrupt for event SLEEPEXIT
        @ReadWrite(bits: 6..<7)
        var sleepexit: SLEEPEXIT

        /// Write '1' to enable interrupt for event USBDETECTED
        @ReadWrite(bits: 7..<8)
        var usbdetected: USBDETECTED

        /// Write '1' to enable interrupt for event USBREMOVED
        @ReadWrite(bits: 8..<9)
        var usbremoved: USBREMOVED

        /// Write '1' to enable interrupt for event USBPWRRDY
        @ReadWrite(bits: 9..<10)
        var usbpwrrdy: USBPWRRDY
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event POFWARN
        @ReadWrite(bits: 2..<3)
        var pofwarn: POFWARN

        /// Write '1' to disable interrupt for event SLEEPENTER
        @ReadWrite(bits: 5..<6)
        var sleepenter: SLEEPENTER

        /// Write '1' to disable interrupt for event SLEEPEXIT
        @ReadWrite(bits: 6..<7)
        var sleepexit: SLEEPEXIT

        /// Write '1' to disable interrupt for event USBDETECTED
        @ReadWrite(bits: 7..<8)
        var usbdetected: USBDETECTED

        /// Write '1' to disable interrupt for event USBREMOVED
        @ReadWrite(bits: 8..<9)
        var usbremoved: USBREMOVED

        /// Write '1' to disable interrupt for event USBPWRRDY
        @ReadWrite(bits: 9..<10)
        var usbpwrrdy: USBPWRRDY
    }

    /// Reset reason
    @Register(bitWidth: 32)
    struct RESETREAS {
        /// Reset from pin-reset detected
        @ReadWrite(bits: 0..<1, as: RESETPINValues.self)
        var resetpin: RESETPIN

        /// Reset from watchdog detected
        @ReadWrite(bits: 1..<2, as: DOGValues.self)
        var dog: DOG

        /// Reset from soft reset detected
        @ReadWrite(bits: 2..<3, as: SREQValues.self)
        var sreq: SREQ

        /// Reset from CPU lock-up detected
        @ReadWrite(bits: 3..<4, as: LOCKUPValues.self)
        var lockup: LOCKUP

        /// Reset due to wake up from System OFF mode when wakeup is triggered from DETECT signal from GPIO
        @ReadWrite(bits: 16..<17, as: OFFValues.self)
        var off: OFF

        /// Reset due to wake up from System OFF mode when wakeup is triggered from ANADETECT signal from LPCOMP
        @ReadWrite(bits: 17..<18, as: LPCOMPValues.self)
        var lpcomp: LPCOMP

        /// Reset due to wake up from System OFF mode when wakeup is triggered from entering into debug interface mode
        @ReadWrite(bits: 18..<19, as: DIFValues.self)
        var dif: DIF

        /// Reset due to wake up from System OFF mode by NFC field detect
        @ReadWrite(bits: 19..<20, as: NFCValues.self)
        var nfc: NFC

        /// Reset due to wake up from System OFF mode by VBUS rising into valid range
        @ReadWrite(bits: 20..<21, as: VBUSValues.self)
        var vbus: VBUS
    }

    /// Deprecated register - RAM status register
    @Register(bitWidth: 32)
    struct RAMSTATUS {
        /// RAM block 0 is on or off/powering up
        @ReadOnly(bits: 0..<1, as: RAMBLOCK0Values.self)
        var ramblock0: RAMBLOCK0

        /// RAM block 1 is on or off/powering up
        @ReadOnly(bits: 1..<2, as: RAMBLOCK1Values.self)
        var ramblock1: RAMBLOCK1

        /// RAM block 2 is on or off/powering up
        @ReadOnly(bits: 2..<3, as: RAMBLOCK2Values.self)
        var ramblock2: RAMBLOCK2

        /// RAM block 3 is on or off/powering up
        @ReadOnly(bits: 3..<4, as: RAMBLOCK3Values.self)
        var ramblock3: RAMBLOCK3
    }

    /// USB supply status
    @Register(bitWidth: 32)
    struct USBREGSTATUS {
        /// VBUS input detection status (USBDETECTED and USBREMOVED events are derived from this information)
        @ReadOnly(bits: 0..<1, as: VBUSDETECTValues.self)
        var vbusdetect: VBUSDETECT

        /// USB supply output settling time elapsed
        @ReadOnly(bits: 1..<2, as: OUTPUTRDYValues.self)
        var outputrdy: OUTPUTRDY
    }

    /// System OFF register
    @Register(bitWidth: 32)
    struct SYSTEMOFF {
        /// Enable System OFF mode
        @WriteOnly(bits: 0..<1, as: SYSTEMOFF_FIELDValues.self)
        var systemoff_field: SYSTEMOFF_FIELD
    }

    /// Power-fail comparator configuration
    @Register(bitWidth: 32)
    struct POFCON {
        /// Enable or disable power failure warning
        @ReadWrite(bits: 0..<1, as: POFValues.self)
        var pof: POF

        /// Power-fail comparator threshold setting. This setting applies both for normal voltage mode (supply connected to both VDD and VDDH) and high voltage mode (supply connected to VDDH only). Values 0-3 set threshold below 1.7 V and should not be used as brown out detection will be activated before power failure warning on such low voltages.
        @ReadWrite(bits: 1..<5, as: THRESHOLDValues.self)
        var threshold: THRESHOLD

        /// Power-fail comparator threshold setting for high voltage mode (supply connected to VDDH only). This setting does not apply for normal voltage mode (supply connected to both VDD and VDDH).
        @ReadWrite(bits: 8..<12, as: THRESHOLDVDDHValues.self)
        var thresholdvddh: THRESHOLDVDDH
    }

    /// General purpose retention register
    @Register(bitWidth: 32)
    struct GPREGRET {
        /// General purpose retention register
        @ReadWrite(bits: 0..<8)
        var gpregret_field: GPREGRET_FIELD
    }

    /// General purpose retention register
    @Register(bitWidth: 32)
    struct GPREGRET2 {
        /// General purpose retention register
        @ReadWrite(bits: 0..<8)
        var gpregret: GPREGRET
    }

    /// Enable DC/DC converter for REG1 stage
    @Register(bitWidth: 32)
    struct DCDCEN {
        /// Enable DC/DC converter for REG1 stage.
        @ReadWrite(bits: 0..<1, as: DCDCEN_FIELDValues.self)
        var dcdcen_field: DCDCEN_FIELD
    }

    /// Main supply status
    @Register(bitWidth: 32)
    struct MAINREGSTATUS {
        /// Main supply status
        @ReadOnly(bits: 0..<1, as: MAINREGSTATUS_FIELDValues.self)
        var mainregstatus_field: MAINREGSTATUS_FIELD
    }

    /// Unspecified
    @RegisterBlock
    struct RAM {
        /// Description cluster: RAMn power control register
        @RegisterBlock(offset: 0x0)
        var power: Register<POWER>

        /// Description cluster: RAMn power control set register
        @RegisterBlock(offset: 0x4)
        var powerset: Register<POWERSET>

        /// Description cluster: RAMn power control clear register
        @RegisterBlock(offset: 0x8)
        var powerclr: Register<POWERCLR>
    }
}

extension POWER.RAM {
    /// Description cluster: RAMn power control register
    @Register(bitWidth: 32)
    struct POWER {
        /// Keep RAM section S0 on or off in System ON mode.
        @ReadWrite(bits: 0..<1, as: S0POWERValues.self)
        var s0power: S0POWER

        /// Keep RAM section S1 on or off in System ON mode.
        @ReadWrite(bits: 1..<2, as: S1POWERValues.self)
        var s1power: S1POWER

        /// Keep RAM section S2 on or off in System ON mode.
        @ReadWrite(bits: 2..<3, as: S2POWERValues.self)
        var s2power: S2POWER

        /// Keep RAM section S3 on or off in System ON mode.
        @ReadWrite(bits: 3..<4, as: S3POWERValues.self)
        var s3power: S3POWER

        /// Keep RAM section S4 on or off in System ON mode.
        @ReadWrite(bits: 4..<5, as: S4POWERValues.self)
        var s4power: S4POWER

        /// Keep RAM section S5 on or off in System ON mode.
        @ReadWrite(bits: 5..<6, as: S5POWERValues.self)
        var s5power: S5POWER

        /// Keep RAM section S6 on or off in System ON mode.
        @ReadWrite(bits: 6..<7, as: S6POWERValues.self)
        var s6power: S6POWER

        /// Keep RAM section S7 on or off in System ON mode.
        @ReadWrite(bits: 7..<8, as: S7POWERValues.self)
        var s7power: S7POWER

        /// Keep RAM section S8 on or off in System ON mode.
        @ReadWrite(bits: 8..<9, as: S8POWERValues.self)
        var s8power: S8POWER

        /// Keep RAM section S9 on or off in System ON mode.
        @ReadWrite(bits: 9..<10, as: S9POWERValues.self)
        var s9power: S9POWER

        /// Keep RAM section S10 on or off in System ON mode.
        @ReadWrite(bits: 10..<11, as: S10POWERValues.self)
        var s10power: S10POWER

        /// Keep RAM section S11 on or off in System ON mode.
        @ReadWrite(bits: 11..<12, as: S11POWERValues.self)
        var s11power: S11POWER

        /// Keep RAM section S12 on or off in System ON mode.
        @ReadWrite(bits: 12..<13, as: S12POWERValues.self)
        var s12power: S12POWER

        /// Keep RAM section S13 on or off in System ON mode.
        @ReadWrite(bits: 13..<14, as: S13POWERValues.self)
        var s13power: S13POWER

        /// Keep RAM section S14 on or off in System ON mode.
        @ReadWrite(bits: 14..<15, as: S14POWERValues.self)
        var s14power: S14POWER

        /// Keep RAM section S15 on or off in System ON mode.
        @ReadWrite(bits: 15..<16, as: S15POWERValues.self)
        var s15power: S15POWER

        /// Keep retention on RAM section S0 when RAM section is off
        @ReadWrite(bits: 16..<17, as: S0RETENTIONValues.self)
        var s0retention: S0RETENTION

        /// Keep retention on RAM section S1 when RAM section is off
        @ReadWrite(bits: 17..<18, as: S1RETENTIONValues.self)
        var s1retention: S1RETENTION

        /// Keep retention on RAM section S2 when RAM section is off
        @ReadWrite(bits: 18..<19, as: S2RETENTIONValues.self)
        var s2retention: S2RETENTION

        /// Keep retention on RAM section S3 when RAM section is off
        @ReadWrite(bits: 19..<20, as: S3RETENTIONValues.self)
        var s3retention: S3RETENTION

        /// Keep retention on RAM section S4 when RAM section is off
        @ReadWrite(bits: 20..<21, as: S4RETENTIONValues.self)
        var s4retention: S4RETENTION

        /// Keep retention on RAM section S5 when RAM section is off
        @ReadWrite(bits: 21..<22, as: S5RETENTIONValues.self)
        var s5retention: S5RETENTION

        /// Keep retention on RAM section S6 when RAM section is off
        @ReadWrite(bits: 22..<23, as: S6RETENTIONValues.self)
        var s6retention: S6RETENTION

        /// Keep retention on RAM section S7 when RAM section is off
        @ReadWrite(bits: 23..<24, as: S7RETENTIONValues.self)
        var s7retention: S7RETENTION

        /// Keep retention on RAM section S8 when RAM section is off
        @ReadWrite(bits: 24..<25, as: S8RETENTIONValues.self)
        var s8retention: S8RETENTION

        /// Keep retention on RAM section S9 when RAM section is off
        @ReadWrite(bits: 25..<26, as: S9RETENTIONValues.self)
        var s9retention: S9RETENTION

        /// Keep retention on RAM section S10 when RAM section is off
        @ReadWrite(bits: 26..<27, as: S10RETENTIONValues.self)
        var s10retention: S10RETENTION

        /// Keep retention on RAM section S11 when RAM section is off
        @ReadWrite(bits: 27..<28, as: S11RETENTIONValues.self)
        var s11retention: S11RETENTION

        /// Keep retention on RAM section S12 when RAM section is off
        @ReadWrite(bits: 28..<29, as: S12RETENTIONValues.self)
        var s12retention: S12RETENTION

        /// Keep retention on RAM section S13 when RAM section is off
        @ReadWrite(bits: 29..<30, as: S13RETENTIONValues.self)
        var s13retention: S13RETENTION

        /// Keep retention on RAM section S14 when RAM section is off
        @ReadWrite(bits: 30..<31, as: S14RETENTIONValues.self)
        var s14retention: S14RETENTION

        /// Keep retention on RAM section S15 when RAM section is off
        @ReadWrite(bits: 31..<32, as: S15RETENTIONValues.self)
        var s15retention: S15RETENTION
    }

    /// Description cluster: RAMn power control set register
    @Register(bitWidth: 32)
    struct POWERSET {
        /// Keep RAM section S0 of RAMn on or off in System ON mode
        @WriteOnly(bits: 0..<1, as: S0POWERValues.self)
        var s0power: S0POWER

        /// Keep RAM section S1 of RAMn on or off in System ON mode
        @WriteOnly(bits: 1..<2, as: S1POWERValues.self)
        var s1power: S1POWER

        /// Keep RAM section S2 of RAMn on or off in System ON mode
        @WriteOnly(bits: 2..<3, as: S2POWERValues.self)
        var s2power: S2POWER

        /// Keep RAM section S3 of RAMn on or off in System ON mode
        @WriteOnly(bits: 3..<4, as: S3POWERValues.self)
        var s3power: S3POWER

        /// Keep RAM section S4 of RAMn on or off in System ON mode
        @WriteOnly(bits: 4..<5, as: S4POWERValues.self)
        var s4power: S4POWER

        /// Keep RAM section S5 of RAMn on or off in System ON mode
        @WriteOnly(bits: 5..<6, as: S5POWERValues.self)
        var s5power: S5POWER

        /// Keep RAM section S6 of RAMn on or off in System ON mode
        @WriteOnly(bits: 6..<7, as: S6POWERValues.self)
        var s6power: S6POWER

        /// Keep RAM section S7 of RAMn on or off in System ON mode
        @WriteOnly(bits: 7..<8, as: S7POWERValues.self)
        var s7power: S7POWER

        /// Keep RAM section S8 of RAMn on or off in System ON mode
        @WriteOnly(bits: 8..<9, as: S8POWERValues.self)
        var s8power: S8POWER

        /// Keep RAM section S9 of RAMn on or off in System ON mode
        @WriteOnly(bits: 9..<10, as: S9POWERValues.self)
        var s9power: S9POWER

        /// Keep RAM section S10 of RAMn on or off in System ON mode
        @WriteOnly(bits: 10..<11, as: S10POWERValues.self)
        var s10power: S10POWER

        /// Keep RAM section S11 of RAMn on or off in System ON mode
        @WriteOnly(bits: 11..<12, as: S11POWERValues.self)
        var s11power: S11POWER

        /// Keep RAM section S12 of RAMn on or off in System ON mode
        @WriteOnly(bits: 12..<13, as: S12POWERValues.self)
        var s12power: S12POWER

        /// Keep RAM section S13 of RAMn on or off in System ON mode
        @WriteOnly(bits: 13..<14, as: S13POWERValues.self)
        var s13power: S13POWER

        /// Keep RAM section S14 of RAMn on or off in System ON mode
        @WriteOnly(bits: 14..<15, as: S14POWERValues.self)
        var s14power: S14POWER

        /// Keep RAM section S15 of RAMn on or off in System ON mode
        @WriteOnly(bits: 15..<16, as: S15POWERValues.self)
        var s15power: S15POWER

        /// Keep retention on RAM section S0 when RAM section is switched off
        @WriteOnly(bits: 16..<17, as: S0RETENTIONValues.self)
        var s0retention: S0RETENTION

        /// Keep retention on RAM section S1 when RAM section is switched off
        @WriteOnly(bits: 17..<18, as: S1RETENTIONValues.self)
        var s1retention: S1RETENTION

        /// Keep retention on RAM section S2 when RAM section is switched off
        @WriteOnly(bits: 18..<19, as: S2RETENTIONValues.self)
        var s2retention: S2RETENTION

        /// Keep retention on RAM section S3 when RAM section is switched off
        @WriteOnly(bits: 19..<20, as: S3RETENTIONValues.self)
        var s3retention: S3RETENTION

        /// Keep retention on RAM section S4 when RAM section is switched off
        @WriteOnly(bits: 20..<21, as: S4RETENTIONValues.self)
        var s4retention: S4RETENTION

        /// Keep retention on RAM section S5 when RAM section is switched off
        @WriteOnly(bits: 21..<22, as: S5RETENTIONValues.self)
        var s5retention: S5RETENTION

        /// Keep retention on RAM section S6 when RAM section is switched off
        @WriteOnly(bits: 22..<23, as: S6RETENTIONValues.self)
        var s6retention: S6RETENTION

        /// Keep retention on RAM section S7 when RAM section is switched off
        @WriteOnly(bits: 23..<24, as: S7RETENTIONValues.self)
        var s7retention: S7RETENTION

        /// Keep retention on RAM section S8 when RAM section is switched off
        @WriteOnly(bits: 24..<25, as: S8RETENTIONValues.self)
        var s8retention: S8RETENTION

        /// Keep retention on RAM section S9 when RAM section is switched off
        @WriteOnly(bits: 25..<26, as: S9RETENTIONValues.self)
        var s9retention: S9RETENTION

        /// Keep retention on RAM section S10 when RAM section is switched off
        @WriteOnly(bits: 26..<27, as: S10RETENTIONValues.self)
        var s10retention: S10RETENTION

        /// Keep retention on RAM section S11 when RAM section is switched off
        @WriteOnly(bits: 27..<28, as: S11RETENTIONValues.self)
        var s11retention: S11RETENTION

        /// Keep retention on RAM section S12 when RAM section is switched off
        @WriteOnly(bits: 28..<29, as: S12RETENTIONValues.self)
        var s12retention: S12RETENTION

        /// Keep retention on RAM section S13 when RAM section is switched off
        @WriteOnly(bits: 29..<30, as: S13RETENTIONValues.self)
        var s13retention: S13RETENTION

        /// Keep retention on RAM section S14 when RAM section is switched off
        @WriteOnly(bits: 30..<31, as: S14RETENTIONValues.self)
        var s14retention: S14RETENTION

        /// Keep retention on RAM section S15 when RAM section is switched off
        @WriteOnly(bits: 31..<32, as: S15RETENTIONValues.self)
        var s15retention: S15RETENTION
    }

    /// Description cluster: RAMn power control clear register
    @Register(bitWidth: 32)
    struct POWERCLR {
        /// Keep RAM section S0 of RAMn on or off in System ON mode
        @WriteOnly(bits: 0..<1, as: S0POWERValues.self)
        var s0power: S0POWER

        /// Keep RAM section S1 of RAMn on or off in System ON mode
        @WriteOnly(bits: 1..<2, as: S1POWERValues.self)
        var s1power: S1POWER

        /// Keep RAM section S2 of RAMn on or off in System ON mode
        @WriteOnly(bits: 2..<3, as: S2POWERValues.self)
        var s2power: S2POWER

        /// Keep RAM section S3 of RAMn on or off in System ON mode
        @WriteOnly(bits: 3..<4, as: S3POWERValues.self)
        var s3power: S3POWER

        /// Keep RAM section S4 of RAMn on or off in System ON mode
        @WriteOnly(bits: 4..<5, as: S4POWERValues.self)
        var s4power: S4POWER

        /// Keep RAM section S5 of RAMn on or off in System ON mode
        @WriteOnly(bits: 5..<6, as: S5POWERValues.self)
        var s5power: S5POWER

        /// Keep RAM section S6 of RAMn on or off in System ON mode
        @WriteOnly(bits: 6..<7, as: S6POWERValues.self)
        var s6power: S6POWER

        /// Keep RAM section S7 of RAMn on or off in System ON mode
        @WriteOnly(bits: 7..<8, as: S7POWERValues.self)
        var s7power: S7POWER

        /// Keep RAM section S8 of RAMn on or off in System ON mode
        @WriteOnly(bits: 8..<9, as: S8POWERValues.self)
        var s8power: S8POWER

        /// Keep RAM section S9 of RAMn on or off in System ON mode
        @WriteOnly(bits: 9..<10, as: S9POWERValues.self)
        var s9power: S9POWER

        /// Keep RAM section S10 of RAMn on or off in System ON mode
        @WriteOnly(bits: 10..<11, as: S10POWERValues.self)
        var s10power: S10POWER

        /// Keep RAM section S11 of RAMn on or off in System ON mode
        @WriteOnly(bits: 11..<12, as: S11POWERValues.self)
        var s11power: S11POWER

        /// Keep RAM section S12 of RAMn on or off in System ON mode
        @WriteOnly(bits: 12..<13, as: S12POWERValues.self)
        var s12power: S12POWER

        /// Keep RAM section S13 of RAMn on or off in System ON mode
        @WriteOnly(bits: 13..<14, as: S13POWERValues.self)
        var s13power: S13POWER

        /// Keep RAM section S14 of RAMn on or off in System ON mode
        @WriteOnly(bits: 14..<15, as: S14POWERValues.self)
        var s14power: S14POWER

        /// Keep RAM section S15 of RAMn on or off in System ON mode
        @WriteOnly(bits: 15..<16, as: S15POWERValues.self)
        var s15power: S15POWER

        /// Keep retention on RAM section S0 when RAM section is switched off
        @WriteOnly(bits: 16..<17, as: S0RETENTIONValues.self)
        var s0retention: S0RETENTION

        /// Keep retention on RAM section S1 when RAM section is switched off
        @WriteOnly(bits: 17..<18, as: S1RETENTIONValues.self)
        var s1retention: S1RETENTION

        /// Keep retention on RAM section S2 when RAM section is switched off
        @WriteOnly(bits: 18..<19, as: S2RETENTIONValues.self)
        var s2retention: S2RETENTION

        /// Keep retention on RAM section S3 when RAM section is switched off
        @WriteOnly(bits: 19..<20, as: S3RETENTIONValues.self)
        var s3retention: S3RETENTION

        /// Keep retention on RAM section S4 when RAM section is switched off
        @WriteOnly(bits: 20..<21, as: S4RETENTIONValues.self)
        var s4retention: S4RETENTION

        /// Keep retention on RAM section S5 when RAM section is switched off
        @WriteOnly(bits: 21..<22, as: S5RETENTIONValues.self)
        var s5retention: S5RETENTION

        /// Keep retention on RAM section S6 when RAM section is switched off
        @WriteOnly(bits: 22..<23, as: S6RETENTIONValues.self)
        var s6retention: S6RETENTION

        /// Keep retention on RAM section S7 when RAM section is switched off
        @WriteOnly(bits: 23..<24, as: S7RETENTIONValues.self)
        var s7retention: S7RETENTION

        /// Keep retention on RAM section S8 when RAM section is switched off
        @WriteOnly(bits: 24..<25, as: S8RETENTIONValues.self)
        var s8retention: S8RETENTION

        /// Keep retention on RAM section S9 when RAM section is switched off
        @WriteOnly(bits: 25..<26, as: S9RETENTIONValues.self)
        var s9retention: S9RETENTION

        /// Keep retention on RAM section S10 when RAM section is switched off
        @WriteOnly(bits: 26..<27, as: S10RETENTIONValues.self)
        var s10retention: S10RETENTION

        /// Keep retention on RAM section S11 when RAM section is switched off
        @WriteOnly(bits: 27..<28, as: S11RETENTIONValues.self)
        var s11retention: S11RETENTION

        /// Keep retention on RAM section S12 when RAM section is switched off
        @WriteOnly(bits: 28..<29, as: S12RETENTIONValues.self)
        var s12retention: S12RETENTION

        /// Keep retention on RAM section S13 when RAM section is switched off
        @WriteOnly(bits: 29..<30, as: S13RETENTIONValues.self)
        var s13retention: S13RETENTION

        /// Keep retention on RAM section S14 when RAM section is switched off
        @WriteOnly(bits: 30..<31, as: S14RETENTIONValues.self)
        var s14retention: S14RETENTION

        /// Keep retention on RAM section S15 when RAM section is switched off
        @WriteOnly(bits: 31..<32, as: S15RETENTIONValues.self)
        var s15retention: S15RETENTION
    }
}

extension POWER.TASKS_CONSTLAT {
    struct TASKS_CONSTLAT_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.TASKS_LOWPWR {
    struct TASKS_LOWPWR_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.EVENTS_POFWARN {
    struct EVENTS_POFWARN_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.EVENTS_SLEEPENTER {
    struct EVENTS_SLEEPENTER_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.EVENTS_SLEEPEXIT {
    struct EVENTS_SLEEPEXIT_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.EVENTS_USBDETECTED {
    struct EVENTS_USBDETECTED_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.EVENTS_USBREMOVED {
    struct EVENTS_USBREMOVED_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.EVENTS_USBPWRRDY {
    struct EVENTS_USBPWRRDY_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct RESETPINValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct DOGValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct SREQValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct LOCKUPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct OFFValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct LPCOMPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct DIFValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct NFCValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RESETREAS {
    struct VBUSValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Not detected
        static let NotDetected = Self(rawValue: 0x0)

        /// Detected
        static let Detected = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAMSTATUS {
    struct RAMBLOCK0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAMSTATUS {
    struct RAMBLOCK1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAMSTATUS {
    struct RAMBLOCK2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAMSTATUS {
    struct RAMBLOCK3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.USBREGSTATUS {
    struct VBUSDETECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// VBUS voltage below valid threshold
        static let NoVbus = Self(rawValue: 0x0)

        /// VBUS voltage above valid threshold
        static let VbusPresent = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.USBREGSTATUS {
    struct OUTPUTRDYValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// USBREG output settling time not elapsed
        static let NotReady = Self(rawValue: 0x0)

        /// USBREG output settling time elapsed (same information as USBPWRRDY event)
        static let Ready = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.SYSTEMOFF {
    struct SYSTEMOFF_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Enable System OFF mode
        static let Enter = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.POFCON {
    struct POFValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.POFCON {
    struct THRESHOLDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 4

        /// Set threshold to 1.7 V
        static let V17 = Self(rawValue: 0x4)

        /// Set threshold to 1.8 V
        static let V18 = Self(rawValue: 0x5)

        /// Set threshold to 1.9 V
        static let V19 = Self(rawValue: 0x6)

        /// Set threshold to 2.0 V
        static let V20 = Self(rawValue: 0x7)

        /// Set threshold to 2.1 V
        static let V21 = Self(rawValue: 0x8)

        /// Set threshold to 2.2 V
        static let V22 = Self(rawValue: 0x9)

        /// Set threshold to 2.3 V
        static let V23 = Self(rawValue: 0xa)

        /// Set threshold to 2.4 V
        static let V24 = Self(rawValue: 0xb)

        /// Set threshold to 2.5 V
        static let V25 = Self(rawValue: 0xc)

        /// Set threshold to 2.6 V
        static let V26 = Self(rawValue: 0xd)

        /// Set threshold to 2.7 V
        static let V27 = Self(rawValue: 0xe)

        /// Set threshold to 2.8 V
        static let V28 = Self(rawValue: 0xf)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.POFCON {
    struct THRESHOLDVDDHValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 4

        /// Set threshold to 2.7 V
        static let V27 = Self(rawValue: 0x0)

        /// Set threshold to 2.8 V
        static let V28 = Self(rawValue: 0x1)

        /// Set threshold to 2.9 V
        static let V29 = Self(rawValue: 0x2)

        /// Set threshold to 3.0 V
        static let V30 = Self(rawValue: 0x3)

        /// Set threshold to 3.1 V
        static let V31 = Self(rawValue: 0x4)

        /// Set threshold to 3.2 V
        static let V32 = Self(rawValue: 0x5)

        /// Set threshold to 3.3 V
        static let V33 = Self(rawValue: 0x6)

        /// Set threshold to 3.4 V
        static let V34 = Self(rawValue: 0x7)

        /// Set threshold to 3.5 V
        static let V35 = Self(rawValue: 0x8)

        /// Set threshold to 3.6 V
        static let V36 = Self(rawValue: 0x9)

        /// Set threshold to 3.7 V
        static let V37 = Self(rawValue: 0xa)

        /// Set threshold to 3.8 V
        static let V38 = Self(rawValue: 0xb)

        /// Set threshold to 3.9 V
        static let V39 = Self(rawValue: 0xc)

        /// Set threshold to 4.0 V
        static let V40 = Self(rawValue: 0xd)

        /// Set threshold to 4.1 V
        static let V41 = Self(rawValue: 0xe)

        /// Set threshold to 4.2 V
        static let V42 = Self(rawValue: 0xf)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.DCDCEN {
    struct DCDCEN_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Enable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.MAINREGSTATUS {
    struct MAINREGSTATUS_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Normal voltage mode. Voltage supplied on VDD.
        static let Normal = Self(rawValue: 0x0)

        /// High voltage mode. Voltage supplied on VDDH.
        static let High = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S0POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S1POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S2POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S3POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S4POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S5POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S6POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S7POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S8POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S9POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S10POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S11POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S12POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S13POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S14POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S15POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S0RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S1RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S2RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S3RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S4RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S5RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S6RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S7RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S8RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S9RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S10RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S11RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S12RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S13RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S14RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWER {
    struct S15RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x0)

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S0POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S1POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S2POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S3POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S4POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S5POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S6POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S7POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S8POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S9POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S10POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S11POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S12POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S13POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S14POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S15POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S0RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S1RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S2RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S3RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S4RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S5RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S6RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S7RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S8RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S9RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S10RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S11RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S12RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S13RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S14RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERSET {
    struct S15RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// On
        static let On = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S0POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S1POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S2POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S3POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S4POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S5POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S6POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S7POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S8POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S9POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S10POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S11POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S12POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S13POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S14POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S15POWERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S0RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S1RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S2RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S3RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S4RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S5RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S6RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S7RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S8RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S9RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S10RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S11RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S12RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S13RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S14RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension POWER.RAM.POWERCLR {
    struct S15RETENTIONValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Off
        static let Off = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
