// Generated by svd2swift.

import MMIO

/// Programmable Peripheral Interconnect
@RegisterBlock
struct PPI {
    /// Channel enable register
    @RegisterBlock(offset: 0x500)
    var chen: Register<CHEN>

    /// Channel enable set register
    @RegisterBlock(offset: 0x504)
    var chenset: Register<CHENSET>

    /// Channel enable clear register
    @RegisterBlock(offset: 0x508)
    var chenclr: Register<CHENCLR>

    /// Description collection: Channel group n
    @RegisterBlock(offset: 0x800, stride: 0x4, count: 6)
    var chg: RegisterArray<CHG>

    /// Channel group tasks
    @RegisterBlock(offset: 0x0, stride: 0x8, count: 6)
    var tasks_chg: RegisterArray<TASKS_CHG>

    /// PPI Channel
    @RegisterBlock(offset: 0x510, stride: 0x8, count: 20)
    var ch: RegisterArray<CH>

    /// Fork
    @RegisterBlock(offset: 0x910, stride: 0x4, count: 32)
    var fork: RegisterArray<FORK>
}

extension PPI {
    /// Channel enable register
    @Register(bitWidth: 32)
    struct CHEN {
        /// Enable or disable channel 0
        @ReadWrite(bits: 0..<1, as: CH0Values.self)
        var ch0: CH0

        /// Enable or disable channel 1
        @ReadWrite(bits: 1..<2, as: CH1Values.self)
        var ch1: CH1

        /// Enable or disable channel 2
        @ReadWrite(bits: 2..<3, as: CH2Values.self)
        var ch2: CH2

        /// Enable or disable channel 3
        @ReadWrite(bits: 3..<4, as: CH3Values.self)
        var ch3: CH3

        /// Enable or disable channel 4
        @ReadWrite(bits: 4..<5, as: CH4Values.self)
        var ch4: CH4

        /// Enable or disable channel 5
        @ReadWrite(bits: 5..<6, as: CH5Values.self)
        var ch5: CH5

        /// Enable or disable channel 6
        @ReadWrite(bits: 6..<7, as: CH6Values.self)
        var ch6: CH6

        /// Enable or disable channel 7
        @ReadWrite(bits: 7..<8, as: CH7Values.self)
        var ch7: CH7

        /// Enable or disable channel 8
        @ReadWrite(bits: 8..<9, as: CH8Values.self)
        var ch8: CH8

        /// Enable or disable channel 9
        @ReadWrite(bits: 9..<10, as: CH9Values.self)
        var ch9: CH9

        /// Enable or disable channel 10
        @ReadWrite(bits: 10..<11, as: CH10Values.self)
        var ch10: CH10

        /// Enable or disable channel 11
        @ReadWrite(bits: 11..<12, as: CH11Values.self)
        var ch11: CH11

        /// Enable or disable channel 12
        @ReadWrite(bits: 12..<13, as: CH12Values.self)
        var ch12: CH12

        /// Enable or disable channel 13
        @ReadWrite(bits: 13..<14, as: CH13Values.self)
        var ch13: CH13

        /// Enable or disable channel 14
        @ReadWrite(bits: 14..<15, as: CH14Values.self)
        var ch14: CH14

        /// Enable or disable channel 15
        @ReadWrite(bits: 15..<16, as: CH15Values.self)
        var ch15: CH15

        /// Enable or disable channel 16
        @ReadWrite(bits: 16..<17, as: CH16Values.self)
        var ch16: CH16

        /// Enable or disable channel 17
        @ReadWrite(bits: 17..<18, as: CH17Values.self)
        var ch17: CH17

        /// Enable or disable channel 18
        @ReadWrite(bits: 18..<19, as: CH18Values.self)
        var ch18: CH18

        /// Enable or disable channel 19
        @ReadWrite(bits: 19..<20, as: CH19Values.self)
        var ch19: CH19

        /// Enable or disable channel 20
        @ReadWrite(bits: 20..<21, as: CH20Values.self)
        var ch20: CH20

        /// Enable or disable channel 21
        @ReadWrite(bits: 21..<22, as: CH21Values.self)
        var ch21: CH21

        /// Enable or disable channel 22
        @ReadWrite(bits: 22..<23, as: CH22Values.self)
        var ch22: CH22

        /// Enable or disable channel 23
        @ReadWrite(bits: 23..<24, as: CH23Values.self)
        var ch23: CH23

        /// Enable or disable channel 24
        @ReadWrite(bits: 24..<25, as: CH24Values.self)
        var ch24: CH24

        /// Enable or disable channel 25
        @ReadWrite(bits: 25..<26, as: CH25Values.self)
        var ch25: CH25

        /// Enable or disable channel 26
        @ReadWrite(bits: 26..<27, as: CH26Values.self)
        var ch26: CH26

        /// Enable or disable channel 27
        @ReadWrite(bits: 27..<28, as: CH27Values.self)
        var ch27: CH27

        /// Enable or disable channel 28
        @ReadWrite(bits: 28..<29, as: CH28Values.self)
        var ch28: CH28

        /// Enable or disable channel 29
        @ReadWrite(bits: 29..<30, as: CH29Values.self)
        var ch29: CH29

        /// Enable or disable channel 30
        @ReadWrite(bits: 30..<31, as: CH30Values.self)
        var ch30: CH30

        /// Enable or disable channel 31
        @ReadWrite(bits: 31..<32, as: CH31Values.self)
        var ch31: CH31
    }

    /// Channel enable set register
    @Register(bitWidth: 32)
    struct CHENSET {
        /// Channel 0 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 0..<1)
        var ch0: CH0

        /// Channel 1 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 1..<2)
        var ch1: CH1

        /// Channel 2 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 2..<3)
        var ch2: CH2

        /// Channel 3 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 3..<4)
        var ch3: CH3

        /// Channel 4 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 4..<5)
        var ch4: CH4

        /// Channel 5 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 5..<6)
        var ch5: CH5

        /// Channel 6 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 6..<7)
        var ch6: CH6

        /// Channel 7 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 7..<8)
        var ch7: CH7

        /// Channel 8 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 8..<9)
        var ch8: CH8

        /// Channel 9 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 9..<10)
        var ch9: CH9

        /// Channel 10 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 10..<11)
        var ch10: CH10

        /// Channel 11 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 11..<12)
        var ch11: CH11

        /// Channel 12 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 12..<13)
        var ch12: CH12

        /// Channel 13 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 13..<14)
        var ch13: CH13

        /// Channel 14 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 14..<15)
        var ch14: CH14

        /// Channel 15 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 15..<16)
        var ch15: CH15

        /// Channel 16 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 16..<17)
        var ch16: CH16

        /// Channel 17 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 17..<18)
        var ch17: CH17

        /// Channel 18 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 18..<19)
        var ch18: CH18

        /// Channel 19 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 19..<20)
        var ch19: CH19

        /// Channel 20 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 20..<21)
        var ch20: CH20

        /// Channel 21 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 21..<22)
        var ch21: CH21

        /// Channel 22 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 22..<23)
        var ch22: CH22

        /// Channel 23 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 23..<24)
        var ch23: CH23

        /// Channel 24 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 24..<25)
        var ch24: CH24

        /// Channel 25 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 25..<26)
        var ch25: CH25

        /// Channel 26 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 26..<27)
        var ch26: CH26

        /// Channel 27 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 27..<28)
        var ch27: CH27

        /// Channel 28 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 28..<29)
        var ch28: CH28

        /// Channel 29 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 29..<30)
        var ch29: CH29

        /// Channel 30 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 30..<31)
        var ch30: CH30

        /// Channel 31 enable set register. Writing '0' has no effect.
        @ReadWrite(bits: 31..<32)
        var ch31: CH31
    }

    /// Channel enable clear register
    @Register(bitWidth: 32)
    struct CHENCLR {
        /// Channel 0 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 0..<1)
        var ch0: CH0

        /// Channel 1 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 1..<2)
        var ch1: CH1

        /// Channel 2 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 2..<3)
        var ch2: CH2

        /// Channel 3 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 3..<4)
        var ch3: CH3

        /// Channel 4 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 4..<5)
        var ch4: CH4

        /// Channel 5 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 5..<6)
        var ch5: CH5

        /// Channel 6 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 6..<7)
        var ch6: CH6

        /// Channel 7 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 7..<8)
        var ch7: CH7

        /// Channel 8 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 8..<9)
        var ch8: CH8

        /// Channel 9 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 9..<10)
        var ch9: CH9

        /// Channel 10 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 10..<11)
        var ch10: CH10

        /// Channel 11 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 11..<12)
        var ch11: CH11

        /// Channel 12 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 12..<13)
        var ch12: CH12

        /// Channel 13 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 13..<14)
        var ch13: CH13

        /// Channel 14 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 14..<15)
        var ch14: CH14

        /// Channel 15 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 15..<16)
        var ch15: CH15

        /// Channel 16 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 16..<17)
        var ch16: CH16

        /// Channel 17 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 17..<18)
        var ch17: CH17

        /// Channel 18 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 18..<19)
        var ch18: CH18

        /// Channel 19 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 19..<20)
        var ch19: CH19

        /// Channel 20 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 20..<21)
        var ch20: CH20

        /// Channel 21 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 21..<22)
        var ch21: CH21

        /// Channel 22 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 22..<23)
        var ch22: CH22

        /// Channel 23 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 23..<24)
        var ch23: CH23

        /// Channel 24 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 24..<25)
        var ch24: CH24

        /// Channel 25 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 25..<26)
        var ch25: CH25

        /// Channel 26 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 26..<27)
        var ch26: CH26

        /// Channel 27 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 27..<28)
        var ch27: CH27

        /// Channel 28 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 28..<29)
        var ch28: CH28

        /// Channel 29 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 29..<30)
        var ch29: CH29

        /// Channel 30 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 30..<31)
        var ch30: CH30

        /// Channel 31 enable clear register. Writing '0' has no effect.
        @ReadWrite(bits: 31..<32)
        var ch31: CH31
    }

    /// Description collection: Channel group n
    @Register(bitWidth: 32)
    struct CHG {
        /// Include or exclude channel 0
        @ReadWrite(bits: 0..<1, as: CH0Values.self)
        var ch0: CH0

        /// Include or exclude channel 1
        @ReadWrite(bits: 1..<2, as: CH1Values.self)
        var ch1: CH1

        /// Include or exclude channel 2
        @ReadWrite(bits: 2..<3, as: CH2Values.self)
        var ch2: CH2

        /// Include or exclude channel 3
        @ReadWrite(bits: 3..<4, as: CH3Values.self)
        var ch3: CH3

        /// Include or exclude channel 4
        @ReadWrite(bits: 4..<5, as: CH4Values.self)
        var ch4: CH4

        /// Include or exclude channel 5
        @ReadWrite(bits: 5..<6, as: CH5Values.self)
        var ch5: CH5

        /// Include or exclude channel 6
        @ReadWrite(bits: 6..<7, as: CH6Values.self)
        var ch6: CH6

        /// Include or exclude channel 7
        @ReadWrite(bits: 7..<8, as: CH7Values.self)
        var ch7: CH7

        /// Include or exclude channel 8
        @ReadWrite(bits: 8..<9, as: CH8Values.self)
        var ch8: CH8

        /// Include or exclude channel 9
        @ReadWrite(bits: 9..<10, as: CH9Values.self)
        var ch9: CH9

        /// Include or exclude channel 10
        @ReadWrite(bits: 10..<11, as: CH10Values.self)
        var ch10: CH10

        /// Include or exclude channel 11
        @ReadWrite(bits: 11..<12, as: CH11Values.self)
        var ch11: CH11

        /// Include or exclude channel 12
        @ReadWrite(bits: 12..<13, as: CH12Values.self)
        var ch12: CH12

        /// Include or exclude channel 13
        @ReadWrite(bits: 13..<14, as: CH13Values.self)
        var ch13: CH13

        /// Include or exclude channel 14
        @ReadWrite(bits: 14..<15, as: CH14Values.self)
        var ch14: CH14

        /// Include or exclude channel 15
        @ReadWrite(bits: 15..<16, as: CH15Values.self)
        var ch15: CH15

        /// Include or exclude channel 16
        @ReadWrite(bits: 16..<17, as: CH16Values.self)
        var ch16: CH16

        /// Include or exclude channel 17
        @ReadWrite(bits: 17..<18, as: CH17Values.self)
        var ch17: CH17

        /// Include or exclude channel 18
        @ReadWrite(bits: 18..<19, as: CH18Values.self)
        var ch18: CH18

        /// Include or exclude channel 19
        @ReadWrite(bits: 19..<20, as: CH19Values.self)
        var ch19: CH19

        /// Include or exclude channel 20
        @ReadWrite(bits: 20..<21, as: CH20Values.self)
        var ch20: CH20

        /// Include or exclude channel 21
        @ReadWrite(bits: 21..<22, as: CH21Values.self)
        var ch21: CH21

        /// Include or exclude channel 22
        @ReadWrite(bits: 22..<23, as: CH22Values.self)
        var ch22: CH22

        /// Include or exclude channel 23
        @ReadWrite(bits: 23..<24, as: CH23Values.self)
        var ch23: CH23

        /// Include or exclude channel 24
        @ReadWrite(bits: 24..<25, as: CH24Values.self)
        var ch24: CH24

        /// Include or exclude channel 25
        @ReadWrite(bits: 25..<26, as: CH25Values.self)
        var ch25: CH25

        /// Include or exclude channel 26
        @ReadWrite(bits: 26..<27, as: CH26Values.self)
        var ch26: CH26

        /// Include or exclude channel 27
        @ReadWrite(bits: 27..<28, as: CH27Values.self)
        var ch27: CH27

        /// Include or exclude channel 28
        @ReadWrite(bits: 28..<29, as: CH28Values.self)
        var ch28: CH28

        /// Include or exclude channel 29
        @ReadWrite(bits: 29..<30, as: CH29Values.self)
        var ch29: CH29

        /// Include or exclude channel 30
        @ReadWrite(bits: 30..<31, as: CH30Values.self)
        var ch30: CH30

        /// Include or exclude channel 31
        @ReadWrite(bits: 31..<32, as: CH31Values.self)
        var ch31: CH31
    }

    /// Channel group tasks
    @RegisterBlock
    struct TASKS_CHG {
        /// Description cluster: Enable channel group n
        @RegisterBlock(offset: 0x0)
        var en: Register<EN>

        /// Description cluster: Disable channel group n
        @RegisterBlock(offset: 0x4)
        var dis: Register<DIS>
    }

    /// PPI Channel
    @RegisterBlock
    struct CH {
        /// Description cluster: Channel n event endpoint
        @RegisterBlock(offset: 0x0)
        var eep: Register<EEP>

        /// Description cluster: Channel n task endpoint
        @RegisterBlock(offset: 0x4)
        var tep: Register<TEP>
    }

    /// Fork
    @RegisterBlock
    struct FORK {
        /// Description cluster: Channel n task endpoint
        @RegisterBlock(offset: 0x0)
        var tep: Register<TEP>
    }
}

extension PPI.TASKS_CHG {
    /// Description cluster: Enable channel group n
    @Register(bitWidth: 32)
    struct EN {
        /// Enable channel group n
        @WriteOnly(bits: 0..<1, as: EN_FIELDValues.self)
        var en_field: EN_FIELD
    }

    /// Description cluster: Disable channel group n
    @Register(bitWidth: 32)
    struct DIS {
        /// Disable channel group n
        @WriteOnly(bits: 0..<1, as: DIS_FIELDValues.self)
        var dis_field: DIS_FIELD
    }
}

extension PPI.CH {
    /// Description cluster: Channel n event endpoint
    @Register(bitWidth: 32)
    struct EEP {
        /// Pointer to event register. Accepts only addresses to registers from the Event group.
        @ReadWrite(bits: 0..<32)
        var eep_field: EEP_FIELD
    }

    /// Description cluster: Channel n task endpoint
    @Register(bitWidth: 32)
    struct TEP {
        /// Pointer to task register. Accepts only addresses to registers from the Task group.
        @ReadWrite(bits: 0..<32)
        var tep_field: TEP_FIELD
    }
}

extension PPI.FORK {
    /// Description cluster: Channel n task endpoint
    @Register(bitWidth: 32)
    struct TEP {
        /// Pointer to task register
        @ReadWrite(bits: 0..<32)
        var tep_field: TEP_FIELD
    }
}

extension PPI.CHEN {
    struct CH0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH4Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH5Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH6Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH7Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH8Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH9Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH10Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH11Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH12Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH13Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH14Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH15Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH16Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH17Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH18Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH19Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH20Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH21Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH22Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH23Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH24Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH25Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH26Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH27Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH28Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH29Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH30Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHEN {
    struct CH31Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable channel
        static let Disabled = Self(rawValue: 0x0)

        /// Enable channel
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH4Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH5Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH6Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH7Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH8Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH9Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH10Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH11Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH12Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH13Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH14Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH15Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH16Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH17Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH18Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH19Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH20Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH21Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH22Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH23Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH24Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH25Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH26Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH27Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH28Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH29Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH30Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.CHG {
    struct CH31Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Exclude
        static let Excluded = Self(rawValue: 0x0)

        /// Include
        static let Included = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.TASKS_CHG.EN {
    struct EN_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension PPI.TASKS_CHG.DIS {
    struct DIS_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
