// Generated by svd2swift.

import MMIO

/// Real time counter 0
@RegisterBlock
struct RTC0 {
    /// Start RTC COUNTER
    @RegisterBlock(offset: 0x0)
    var tasks_start: Register<TASKS_START>

    /// Stop RTC COUNTER
    @RegisterBlock(offset: 0x4)
    var tasks_stop: Register<TASKS_STOP>

    /// Clear RTC COUNTER
    @RegisterBlock(offset: 0x8)
    var tasks_clear: Register<TASKS_CLEAR>

    /// Set COUNTER to 0xFFFFF0
    @RegisterBlock(offset: 0xc)
    var tasks_trigovrflw: Register<TASKS_TRIGOVRFLW>

    /// Event on COUNTER increment
    @RegisterBlock(offset: 0x100)
    var events_tick: Register<EVENTS_TICK>

    /// Event on COUNTER overflow
    @RegisterBlock(offset: 0x104)
    var events_ovrflw: Register<EVENTS_OVRFLW>

    /// Description collection: Compare event on CC[n] match
    @RegisterBlock(offset: 0x140, stride: 0x4, count: 4)
    var events_compare: RegisterArray<EVENTS_COMPARE>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// Enable or disable event routing
    @RegisterBlock(offset: 0x340)
    var evten: Register<EVTEN>

    /// Enable event routing
    @RegisterBlock(offset: 0x344)
    var evtenset: Register<EVTENSET>

    /// Disable event routing
    @RegisterBlock(offset: 0x348)
    var evtenclr: Register<EVTENCLR>

    /// Current COUNTER value
    @RegisterBlock(offset: 0x504)
    var counter: Register<COUNTER>

    /// 12 bit prescaler for COUNTER frequency (32768/(PRESCALER+1)). Must be written when RTC is stopped.
    @RegisterBlock(offset: 0x508)
    var prescaler: Register<PRESCALER>

    /// Description collection: Compare register n
    @RegisterBlock(offset: 0x540, stride: 0x4, count: 4)
    var cc: RegisterArray<CC>
}

extension RTC0 {
    /// Start RTC COUNTER
    @Register(bitWidth: 32)
    struct TASKS_START {
        /// Start RTC COUNTER
        @WriteOnly(bits: 0..<1, as: TASKS_START_FIELDValues.self)
        var tasks_start_field: TASKS_START_FIELD
    }

    /// Stop RTC COUNTER
    @Register(bitWidth: 32)
    struct TASKS_STOP {
        /// Stop RTC COUNTER
        @WriteOnly(bits: 0..<1, as: TASKS_STOP_FIELDValues.self)
        var tasks_stop_field: TASKS_STOP_FIELD
    }

    /// Clear RTC COUNTER
    @Register(bitWidth: 32)
    struct TASKS_CLEAR {
        /// Clear RTC COUNTER
        @WriteOnly(bits: 0..<1, as: TASKS_CLEAR_FIELDValues.self)
        var tasks_clear_field: TASKS_CLEAR_FIELD
    }

    /// Set COUNTER to 0xFFFFF0
    @Register(bitWidth: 32)
    struct TASKS_TRIGOVRFLW {
        /// Set COUNTER to 0xFFFFF0
        @WriteOnly(bits: 0..<1, as: TASKS_TRIGOVRFLW_FIELDValues.self)
        var tasks_trigovrflw_field: TASKS_TRIGOVRFLW_FIELD
    }

    /// Event on COUNTER increment
    @Register(bitWidth: 32)
    struct EVENTS_TICK {
        /// Event on COUNTER increment
        @ReadWrite(bits: 0..<1, as: EVENTS_TICK_FIELDValues.self)
        var events_tick_field: EVENTS_TICK_FIELD
    }

    /// Event on COUNTER overflow
    @Register(bitWidth: 32)
    struct EVENTS_OVRFLW {
        /// Event on COUNTER overflow
        @ReadWrite(bits: 0..<1, as: EVENTS_OVRFLW_FIELDValues.self)
        var events_ovrflw_field: EVENTS_OVRFLW_FIELD
    }

    /// Description collection: Compare event on CC[n] match
    @Register(bitWidth: 32)
    struct EVENTS_COMPARE {
        /// Compare event on CC[n] match
        @ReadWrite(bits: 0..<1, as: EVENTS_COMPARE_FIELDValues.self)
        var events_compare_field: EVENTS_COMPARE_FIELD
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event TICK
        @ReadWrite(bits: 0..<1)
        var tick: TICK

        /// Write '1' to enable interrupt for event OVRFLW
        @ReadWrite(bits: 1..<2)
        var ovrflw: OVRFLW

        /// Write '1' to enable interrupt for event COMPARE[0]
        @ReadWrite(bits: 16..<17)
        var compare0: COMPARE0

        /// Write '1' to enable interrupt for event COMPARE[1]
        @ReadWrite(bits: 17..<18)
        var compare1: COMPARE1

        /// Write '1' to enable interrupt for event COMPARE[2]
        @ReadWrite(bits: 18..<19)
        var compare2: COMPARE2

        /// Write '1' to enable interrupt for event COMPARE[3]
        @ReadWrite(bits: 19..<20)
        var compare3: COMPARE3
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event TICK
        @ReadWrite(bits: 0..<1)
        var tick: TICK

        /// Write '1' to disable interrupt for event OVRFLW
        @ReadWrite(bits: 1..<2)
        var ovrflw: OVRFLW

        /// Write '1' to disable interrupt for event COMPARE[0]
        @ReadWrite(bits: 16..<17)
        var compare0: COMPARE0

        /// Write '1' to disable interrupt for event COMPARE[1]
        @ReadWrite(bits: 17..<18)
        var compare1: COMPARE1

        /// Write '1' to disable interrupt for event COMPARE[2]
        @ReadWrite(bits: 18..<19)
        var compare2: COMPARE2

        /// Write '1' to disable interrupt for event COMPARE[3]
        @ReadWrite(bits: 19..<20)
        var compare3: COMPARE3
    }

    /// Enable or disable event routing
    @Register(bitWidth: 32)
    struct EVTEN {
        /// Enable or disable event routing for event TICK
        @ReadWrite(bits: 0..<1, as: TICKValues.self)
        var tick: TICK

        /// Enable or disable event routing for event OVRFLW
        @ReadWrite(bits: 1..<2, as: OVRFLWValues.self)
        var ovrflw: OVRFLW

        /// Enable or disable event routing for event COMPARE[0]
        @ReadWrite(bits: 16..<17, as: COMPARE0Values.self)
        var compare0: COMPARE0

        /// Enable or disable event routing for event COMPARE[1]
        @ReadWrite(bits: 17..<18, as: COMPARE1Values.self)
        var compare1: COMPARE1

        /// Enable or disable event routing for event COMPARE[2]
        @ReadWrite(bits: 18..<19, as: COMPARE2Values.self)
        var compare2: COMPARE2

        /// Enable or disable event routing for event COMPARE[3]
        @ReadWrite(bits: 19..<20, as: COMPARE3Values.self)
        var compare3: COMPARE3
    }

    /// Enable event routing
    @Register(bitWidth: 32)
    struct EVTENSET {
        /// Write '1' to enable event routing for event TICK
        @ReadWrite(bits: 0..<1)
        var tick: TICK

        /// Write '1' to enable event routing for event OVRFLW
        @ReadWrite(bits: 1..<2)
        var ovrflw: OVRFLW

        /// Write '1' to enable event routing for event COMPARE[0]
        @ReadWrite(bits: 16..<17)
        var compare0: COMPARE0

        /// Write '1' to enable event routing for event COMPARE[1]
        @ReadWrite(bits: 17..<18)
        var compare1: COMPARE1

        /// Write '1' to enable event routing for event COMPARE[2]
        @ReadWrite(bits: 18..<19)
        var compare2: COMPARE2

        /// Write '1' to enable event routing for event COMPARE[3]
        @ReadWrite(bits: 19..<20)
        var compare3: COMPARE3
    }

    /// Disable event routing
    @Register(bitWidth: 32)
    struct EVTENCLR {
        /// Write '1' to disable event routing for event TICK
        @ReadWrite(bits: 0..<1)
        var tick: TICK

        /// Write '1' to disable event routing for event OVRFLW
        @ReadWrite(bits: 1..<2)
        var ovrflw: OVRFLW

        /// Write '1' to disable event routing for event COMPARE[0]
        @ReadWrite(bits: 16..<17)
        var compare0: COMPARE0

        /// Write '1' to disable event routing for event COMPARE[1]
        @ReadWrite(bits: 17..<18)
        var compare1: COMPARE1

        /// Write '1' to disable event routing for event COMPARE[2]
        @ReadWrite(bits: 18..<19)
        var compare2: COMPARE2

        /// Write '1' to disable event routing for event COMPARE[3]
        @ReadWrite(bits: 19..<20)
        var compare3: COMPARE3
    }

    /// Current COUNTER value
    @Register(bitWidth: 32)
    struct COUNTER {
        /// Counter value
        @ReadOnly(bits: 0..<24)
        var counter_field: COUNTER_FIELD
    }

    /// 12 bit prescaler for COUNTER frequency (32768/(PRESCALER+1)). Must be written when RTC is stopped.
    @Register(bitWidth: 32)
    struct PRESCALER {
        /// Prescaler value
        @ReadWrite(bits: 0..<12)
        var prescaler_field: PRESCALER_FIELD
    }

    /// Description collection: Compare register n
    @Register(bitWidth: 32)
    struct CC {
        /// Compare value
        @ReadWrite(bits: 0..<24)
        var compare: COMPARE
    }
}

extension RTC0.TASKS_START {
    struct TASKS_START_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.TASKS_STOP {
    struct TASKS_STOP_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.TASKS_CLEAR {
    struct TASKS_CLEAR_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.TASKS_TRIGOVRFLW {
    struct TASKS_TRIGOVRFLW_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVENTS_TICK {
    struct EVENTS_TICK_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVENTS_OVRFLW {
    struct EVENTS_OVRFLW_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVENTS_COMPARE {
    struct EVENTS_COMPARE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVTEN {
    struct TICKValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Disable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVTEN {
    struct OVRFLWValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Disable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVTEN {
    struct COMPARE0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Disable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVTEN {
    struct COMPARE1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Disable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVTEN {
    struct COMPARE2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Disable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension RTC0.EVTEN {
    struct COMPARE3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable
        static let Disabled = Self(rawValue: 0x0)

        /// Disable
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
