// Generated by svd2swift.

import MMIO

/// Serial Peripheral Interface 0
@RegisterBlock
struct SPI0 {
    /// TXD byte sent and RXD byte received
    @RegisterBlock(offset: 0x108)
    var events_ready: Register<EVENTS_READY>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// Enable SPI
    @RegisterBlock(offset: 0x500)
    var enable: Register<ENABLE>

    /// RXD register
    @RegisterBlock(offset: 0x518)
    var rxd: Register<RXD>

    /// TXD register
    @RegisterBlock(offset: 0x51c)
    var txd: Register<TXD>

    /// SPI frequency. Accuracy depends on the HFCLK source selected.
    @RegisterBlock(offset: 0x524)
    var frequency: Register<FREQUENCY>

    /// Configuration register
    @RegisterBlock(offset: 0x554)
    var config: Register<CONFIG>

    /// Unspecified
    @RegisterBlock(offset: 0x508)
    var psel: PSEL
}

extension SPI0 {
    /// TXD byte sent and RXD byte received
    @Register(bitWidth: 32)
    struct EVENTS_READY {
        /// TXD byte sent and RXD byte received
        @ReadWrite(bits: 0..<1, as: EVENTS_READY_FIELDValues.self)
        var events_ready_field: EVENTS_READY_FIELD
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event READY
        @ReadWrite(bits: 2..<3)
        var ready: READY
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event READY
        @ReadWrite(bits: 2..<3)
        var ready: READY
    }

    /// Enable SPI
    @Register(bitWidth: 32)
    struct ENABLE {
        /// Enable or disable SPI
        @ReadWrite(bits: 0..<4, as: ENABLE_FIELDValues.self)
        var enable_field: ENABLE_FIELD
    }

    /// RXD register
    @Register(bitWidth: 32)
    struct RXD {
        /// RX data received. Double buffered
        @ReadOnly(bits: 0..<8)
        var rxd_field: RXD_FIELD
    }

    /// TXD register
    @Register(bitWidth: 32)
    struct TXD {
        /// TX data to send. Double buffered.
        @ReadWrite(bits: 0..<8)
        var txd_field: TXD_FIELD
    }

    /// SPI frequency. Accuracy depends on the HFCLK source selected.
    @Register(bitWidth: 32)
    struct FREQUENCY {
        /// SPI master data rate
        @ReadWrite(bits: 0..<32, as: FREQUENCY_FIELDValues.self)
        var frequency_field: FREQUENCY_FIELD
    }

    /// Configuration register
    @Register(bitWidth: 32)
    struct CONFIG {
        /// Bit order
        @ReadWrite(bits: 0..<1, as: ORDERValues.self)
        var order: ORDER

        /// Serial clock (SCK) phase
        @ReadWrite(bits: 1..<2, as: CPHAValues.self)
        var cpha: CPHA

        /// Serial clock (SCK) polarity
        @ReadWrite(bits: 2..<3, as: CPOLValues.self)
        var cpol: CPOL
    }

    /// Unspecified
    @RegisterBlock
    struct PSEL {
        /// Pin select for SCK
        @RegisterBlock(offset: 0x0)
        var sck: Register<SCK>

        /// Pin select for MOSI signal
        @RegisterBlock(offset: 0x4)
        var mosi: Register<MOSI>

        /// Pin select for MISO signal
        @RegisterBlock(offset: 0x8)
        var miso: Register<MISO>
    }
}

extension SPI0.PSEL {
    /// Pin select for SCK
    @Register(bitWidth: 32)
    struct SCK {
        /// Pin number
        @ReadWrite(bits: 0..<5)
        var pin: PIN

        /// Port number
        @ReadWrite(bits: 5..<6)
        var port: PORT

        /// Connection
        @ReadWrite(bits: 31..<32, as: CONNECTValues.self)
        var connect: CONNECT
    }

    /// Pin select for MOSI signal
    @Register(bitWidth: 32)
    struct MOSI {
        /// Pin number
        @ReadWrite(bits: 0..<5)
        var pin: PIN

        /// Port number
        @ReadWrite(bits: 5..<6)
        var port: PORT

        /// Connection
        @ReadWrite(bits: 31..<32, as: CONNECTValues.self)
        var connect: CONNECT
    }

    /// Pin select for MISO signal
    @Register(bitWidth: 32)
    struct MISO {
        /// Pin number
        @ReadWrite(bits: 0..<5)
        var pin: PIN

        /// Port number
        @ReadWrite(bits: 5..<6)
        var port: PORT

        /// Connection
        @ReadWrite(bits: 31..<32, as: CONNECTValues.self)
        var connect: CONNECT
    }
}

extension SPI0.EVENTS_READY {
    struct EVENTS_READY_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.ENABLE {
    struct ENABLE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 4

        /// Disable SPI
        static let Disabled = Self(rawValue: 0x0)

        /// Enable SPI
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.FREQUENCY {
    struct FREQUENCY_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 32

        /// 125 kbps
        static let K125 = Self(rawValue: 0x2000000)

        /// 250 kbps
        static let K250 = Self(rawValue: 0x4000000)

        /// 500 kbps
        static let K500 = Self(rawValue: 0x8000000)

        /// 1 Mbps
        static let M1 = Self(rawValue: 0x10000000)

        /// 2 Mbps
        static let M2 = Self(rawValue: 0x20000000)

        /// 4 Mbps
        static let M4 = Self(rawValue: 0x40000000)

        /// 8 Mbps
        static let M8 = Self(rawValue: 0x80000000)

        var rawValue: UInt32

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.CONFIG {
    struct ORDERValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Most significant bit shifted out first
        static let MsbFirst = Self(rawValue: 0x0)

        /// Least significant bit shifted out first
        static let LsbFirst = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.CONFIG {
    struct CPHAValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Sample on leading edge of clock, shift serial data on trailing edge
        static let Leading = Self(rawValue: 0x0)

        /// Sample on trailing edge of clock, shift serial data on leading edge
        static let Trailing = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.CONFIG {
    struct CPOLValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Active high
        static let ActiveHigh = Self(rawValue: 0x0)

        /// Active low
        static let ActiveLow = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.PSEL.SCK {
    struct CONNECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disconnect
        static let Disconnected = Self(rawValue: 0x1)

        /// Connect
        static let Connected = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.PSEL.MOSI {
    struct CONNECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disconnect
        static let Disconnected = Self(rawValue: 0x1)

        /// Connect
        static let Connected = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension SPI0.PSEL.MISO {
    struct CONNECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disconnect
        static let Disconnected = Self(rawValue: 0x1)

        /// Connect
        static let Connected = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
