// Generated by svd2swift.

import MMIO

/// Software interrupt 0
@RegisterBlock
struct SWI0 {
    /// Unused.
    @RegisterBlock(offset: 0x0)
    var unused: Register<UNUSED>
}

extension SWI0 {
    /// Unused.
    @Register(bitWidth: 32)
    struct UNUSED {
    }
}
