// Generated by svd2swift.

import MMIO

/// Timer/Counter 0
@RegisterBlock
struct TIMER0 {
    /// Start Timer
    @RegisterBlock(offset: 0x0)
    var tasks_start: Register<TASKS_START>

    /// Stop Timer
    @RegisterBlock(offset: 0x4)
    var tasks_stop: Register<TASKS_STOP>

    /// Increment Timer (Counter mode only)
    @RegisterBlock(offset: 0x8)
    var tasks_count: Register<TASKS_COUNT>

    /// Clear time
    @RegisterBlock(offset: 0xc)
    var tasks_clear: Register<TASKS_CLEAR>

    /// Deprecated register - Shut down timer
    @RegisterBlock(offset: 0x10)
    var tasks_shutdown: Register<TASKS_SHUTDOWN>

    /// Description collection: Capture Timer value to CC[n] register
    @RegisterBlock(offset: 0x40, stride: 0x4, count: 6)
    var tasks_capture: RegisterArray<TASKS_CAPTURE>

    /// Description collection: Compare event on CC[n] match
    @RegisterBlock(offset: 0x140, stride: 0x4, count: 6)
    var events_compare: RegisterArray<EVENTS_COMPARE>

    /// Shortcuts between local events and tasks
    @RegisterBlock(offset: 0x200)
    var shorts: Register<SHORTS>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// Timer mode selection
    @RegisterBlock(offset: 0x504)
    var mode: Register<MODE>

    /// Configure the number of bits used by the TIMER
    @RegisterBlock(offset: 0x508)
    var bitmode: Register<BITMODE>

    /// Timer prescaler register
    @RegisterBlock(offset: 0x510)
    var prescaler: Register<PRESCALER>

    /// Description collection: Capture/Compare register n
    @RegisterBlock(offset: 0x540, stride: 0x4, count: 6)
    var cc: RegisterArray<CC>
}

extension TIMER0 {
    /// Start Timer
    @Register(bitWidth: 32)
    struct TASKS_START {
        /// Start Timer
        @WriteOnly(bits: 0..<1, as: TASKS_START_FIELDValues.self)
        var tasks_start_field: TASKS_START_FIELD
    }

    /// Stop Timer
    @Register(bitWidth: 32)
    struct TASKS_STOP {
        /// Stop Timer
        @WriteOnly(bits: 0..<1, as: TASKS_STOP_FIELDValues.self)
        var tasks_stop_field: TASKS_STOP_FIELD
    }

    /// Increment Timer (Counter mode only)
    @Register(bitWidth: 32)
    struct TASKS_COUNT {
        /// Increment Timer (Counter mode only)
        @WriteOnly(bits: 0..<1, as: TASKS_COUNT_FIELDValues.self)
        var tasks_count_field: TASKS_COUNT_FIELD
    }

    /// Clear time
    @Register(bitWidth: 32)
    struct TASKS_CLEAR {
        /// Clear time
        @WriteOnly(bits: 0..<1, as: TASKS_CLEAR_FIELDValues.self)
        var tasks_clear_field: TASKS_CLEAR_FIELD
    }

    /// Deprecated register - Shut down timer
    @Register(bitWidth: 32)
    struct TASKS_SHUTDOWN {
        /// Deprecated field - Shut down timer
        @WriteOnly(bits: 0..<1, as: TASKS_SHUTDOWN_FIELDValues.self)
        var tasks_shutdown_field: TASKS_SHUTDOWN_FIELD
    }

    /// Description collection: Capture Timer value to CC[n] register
    @Register(bitWidth: 32)
    struct TASKS_CAPTURE {
        /// Capture Timer value to CC[n] register
        @WriteOnly(bits: 0..<1, as: TASKS_CAPTURE_FIELDValues.self)
        var tasks_capture_field: TASKS_CAPTURE_FIELD
    }

    /// Description collection: Compare event on CC[n] match
    @Register(bitWidth: 32)
    struct EVENTS_COMPARE {
        /// Compare event on CC[n] match
        @ReadWrite(bits: 0..<1, as: EVENTS_COMPARE_FIELDValues.self)
        var events_compare_field: EVENTS_COMPARE_FIELD
    }

    /// Shortcuts between local events and tasks
    @Register(bitWidth: 32)
    struct SHORTS {
        /// Shortcut between event COMPARE[0] and task CLEAR
        @ReadWrite(bits: 0..<1, as: COMPARE0_CLEARValues.self)
        var compare0_clear: COMPARE0_CLEAR

        /// Shortcut between event COMPARE[1] and task CLEAR
        @ReadWrite(bits: 1..<2, as: COMPARE1_CLEARValues.self)
        var compare1_clear: COMPARE1_CLEAR

        /// Shortcut between event COMPARE[2] and task CLEAR
        @ReadWrite(bits: 2..<3, as: COMPARE2_CLEARValues.self)
        var compare2_clear: COMPARE2_CLEAR

        /// Shortcut between event COMPARE[3] and task CLEAR
        @ReadWrite(bits: 3..<4, as: COMPARE3_CLEARValues.self)
        var compare3_clear: COMPARE3_CLEAR

        /// Shortcut between event COMPARE[4] and task CLEAR
        @ReadWrite(bits: 4..<5, as: COMPARE4_CLEARValues.self)
        var compare4_clear: COMPARE4_CLEAR

        /// Shortcut between event COMPARE[5] and task CLEAR
        @ReadWrite(bits: 5..<6, as: COMPARE5_CLEARValues.self)
        var compare5_clear: COMPARE5_CLEAR

        /// Shortcut between event COMPARE[0] and task STOP
        @ReadWrite(bits: 8..<9, as: COMPARE0_STOPValues.self)
        var compare0_stop: COMPARE0_STOP

        /// Shortcut between event COMPARE[1] and task STOP
        @ReadWrite(bits: 9..<10, as: COMPARE1_STOPValues.self)
        var compare1_stop: COMPARE1_STOP

        /// Shortcut between event COMPARE[2] and task STOP
        @ReadWrite(bits: 10..<11, as: COMPARE2_STOPValues.self)
        var compare2_stop: COMPARE2_STOP

        /// Shortcut between event COMPARE[3] and task STOP
        @ReadWrite(bits: 11..<12, as: COMPARE3_STOPValues.self)
        var compare3_stop: COMPARE3_STOP

        /// Shortcut between event COMPARE[4] and task STOP
        @ReadWrite(bits: 12..<13, as: COMPARE4_STOPValues.self)
        var compare4_stop: COMPARE4_STOP

        /// Shortcut between event COMPARE[5] and task STOP
        @ReadWrite(bits: 13..<14, as: COMPARE5_STOPValues.self)
        var compare5_stop: COMPARE5_STOP
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event COMPARE[0]
        @ReadWrite(bits: 16..<17)
        var compare0: COMPARE0

        /// Write '1' to enable interrupt for event COMPARE[1]
        @ReadWrite(bits: 17..<18)
        var compare1: COMPARE1

        /// Write '1' to enable interrupt for event COMPARE[2]
        @ReadWrite(bits: 18..<19)
        var compare2: COMPARE2

        /// Write '1' to enable interrupt for event COMPARE[3]
        @ReadWrite(bits: 19..<20)
        var compare3: COMPARE3

        /// Write '1' to enable interrupt for event COMPARE[4]
        @ReadWrite(bits: 20..<21)
        var compare4: COMPARE4

        /// Write '1' to enable interrupt for event COMPARE[5]
        @ReadWrite(bits: 21..<22)
        var compare5: COMPARE5
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event COMPARE[0]
        @ReadWrite(bits: 16..<17)
        var compare0: COMPARE0

        /// Write '1' to disable interrupt for event COMPARE[1]
        @ReadWrite(bits: 17..<18)
        var compare1: COMPARE1

        /// Write '1' to disable interrupt for event COMPARE[2]
        @ReadWrite(bits: 18..<19)
        var compare2: COMPARE2

        /// Write '1' to disable interrupt for event COMPARE[3]
        @ReadWrite(bits: 19..<20)
        var compare3: COMPARE3

        /// Write '1' to disable interrupt for event COMPARE[4]
        @ReadWrite(bits: 20..<21)
        var compare4: COMPARE4

        /// Write '1' to disable interrupt for event COMPARE[5]
        @ReadWrite(bits: 21..<22)
        var compare5: COMPARE5
    }

    /// Timer mode selection
    @Register(bitWidth: 32)
    struct MODE {
        /// Timer mode
        @ReadWrite(bits: 0..<2, as: MODE_FIELDValues.self)
        var mode_field: MODE_FIELD
    }

    /// Configure the number of bits used by the TIMER
    @Register(bitWidth: 32)
    struct BITMODE {
        /// Timer bit width
        @ReadWrite(bits: 0..<2, as: BITMODE_FIELDValues.self)
        var bitmode_field: BITMODE_FIELD
    }

    /// Timer prescaler register
    @Register(bitWidth: 32)
    struct PRESCALER {
        /// Prescaler value
        @ReadWrite(bits: 0..<4)
        var prescaler_field: PRESCALER_FIELD
    }

    /// Description collection: Capture/Compare register n
    @Register(bitWidth: 32)
    struct CC {
        /// Capture/Compare value
        @ReadWrite(bits: 0..<32)
        var cc_field: CC_FIELD
    }
}

extension TIMER0.TASKS_START {
    struct TASKS_START_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.TASKS_STOP {
    struct TASKS_STOP_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.TASKS_COUNT {
    struct TASKS_COUNT_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.TASKS_CLEAR {
    struct TASKS_CLEAR_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.TASKS_SHUTDOWN {
    struct TASKS_SHUTDOWN_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.TASKS_CAPTURE {
    struct TASKS_CAPTURE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.EVENTS_COMPARE {
    struct EVENTS_COMPARE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE0_CLEARValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE1_CLEARValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE2_CLEARValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE3_CLEARValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE4_CLEARValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE5_CLEARValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE0_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE1_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE2_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE3_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE4_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.SHORTS {
    struct COMPARE5_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.MODE {
    struct MODE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 2

        /// Select Timer mode
        static let Timer = Self(rawValue: 0x0)

        /// Deprecated enumerator -  Select Counter mode
        static let Counter = Self(rawValue: 0x1)

        /// Select Low Power Counter mode
        static let LowPowerCounter = Self(rawValue: 0x2)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TIMER0.BITMODE {
    struct BITMODE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 2

        /// 16 bit timer bit width
        static let _16Bit = Self(rawValue: 0x0)

        /// 8 bit timer bit width
        static let _08Bit = Self(rawValue: 0x1)

        /// 24 bit timer bit width
        static let _24Bit = Self(rawValue: 0x2)

        /// 32 bit timer bit width
        static let _32Bit = Self(rawValue: 0x3)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
