// Generated by svd2swift.

import MMIO

/// I2C compatible Two-Wire Interface 0
@RegisterBlock
struct TWI0 {
    /// Start TWI receive sequence
    @RegisterBlock(offset: 0x0)
    var tasks_startrx: Register<TASKS_STARTRX>

    /// Start TWI transmit sequence
    @RegisterBlock(offset: 0x8)
    var tasks_starttx: Register<TASKS_STARTTX>

    /// Stop TWI transaction
    @RegisterBlock(offset: 0x14)
    var tasks_stop: Register<TASKS_STOP>

    /// Suspend TWI transaction
    @RegisterBlock(offset: 0x1c)
    var tasks_suspend: Register<TASKS_SUSPEND>

    /// Resume TWI transaction
    @RegisterBlock(offset: 0x20)
    var tasks_resume: Register<TASKS_RESUME>

    /// TWI stopped
    @RegisterBlock(offset: 0x104)
    var events_stopped: Register<EVENTS_STOPPED>

    /// TWI RXD byte received
    @RegisterBlock(offset: 0x108)
    var events_rxdready: Register<EVENTS_RXDREADY>

    /// TWI TXD byte sent
    @RegisterBlock(offset: 0x11c)
    var events_txdsent: Register<EVENTS_TXDSENT>

    /// TWI error
    @RegisterBlock(offset: 0x124)
    var events_error: Register<EVENTS_ERROR>

    /// TWI byte boundary, generated before each byte that is sent or received
    @RegisterBlock(offset: 0x138)
    var events_bb: Register<EVENTS_BB>

    /// TWI entered the suspended state
    @RegisterBlock(offset: 0x148)
    var events_suspended: Register<EVENTS_SUSPENDED>

    /// Shortcuts between local events and tasks
    @RegisterBlock(offset: 0x200)
    var shorts: Register<SHORTS>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// Error source
    @RegisterBlock(offset: 0x4c4)
    var errorsrc: Register<ERRORSRC>

    /// Enable TWI
    @RegisterBlock(offset: 0x500)
    var enable: Register<ENABLE>

    /// RXD register
    @RegisterBlock(offset: 0x518)
    var rxd: Register<RXD>

    /// TXD register
    @RegisterBlock(offset: 0x51c)
    var txd: Register<TXD>

    /// TWI frequency. Accuracy depends on the HFCLK source selected.
    @RegisterBlock(offset: 0x524)
    var frequency: Register<FREQUENCY>

    /// Address used in the TWI transfer
    @RegisterBlock(offset: 0x588)
    var address: Register<ADDRESS>

    /// Unspecified
    @RegisterBlock(offset: 0x508)
    var psel: PSEL
}

extension TWI0 {
    /// Start TWI receive sequence
    @Register(bitWidth: 32)
    struct TASKS_STARTRX {
        /// Start TWI receive sequence
        @WriteOnly(bits: 0..<1, as: TASKS_STARTRX_FIELDValues.self)
        var tasks_startrx_field: TASKS_STARTRX_FIELD
    }

    /// Start TWI transmit sequence
    @Register(bitWidth: 32)
    struct TASKS_STARTTX {
        /// Start TWI transmit sequence
        @WriteOnly(bits: 0..<1, as: TASKS_STARTTX_FIELDValues.self)
        var tasks_starttx_field: TASKS_STARTTX_FIELD
    }

    /// Stop TWI transaction
    @Register(bitWidth: 32)
    struct TASKS_STOP {
        /// Stop TWI transaction
        @WriteOnly(bits: 0..<1, as: TASKS_STOP_FIELDValues.self)
        var tasks_stop_field: TASKS_STOP_FIELD
    }

    /// Suspend TWI transaction
    @Register(bitWidth: 32)
    struct TASKS_SUSPEND {
        /// Suspend TWI transaction
        @WriteOnly(bits: 0..<1, as: TASKS_SUSPEND_FIELDValues.self)
        var tasks_suspend_field: TASKS_SUSPEND_FIELD
    }

    /// Resume TWI transaction
    @Register(bitWidth: 32)
    struct TASKS_RESUME {
        /// Resume TWI transaction
        @WriteOnly(bits: 0..<1, as: TASKS_RESUME_FIELDValues.self)
        var tasks_resume_field: TASKS_RESUME_FIELD
    }

    /// TWI stopped
    @Register(bitWidth: 32)
    struct EVENTS_STOPPED {
        /// TWI stopped
        @ReadWrite(bits: 0..<1, as: EVENTS_STOPPED_FIELDValues.self)
        var events_stopped_field: EVENTS_STOPPED_FIELD
    }

    /// TWI RXD byte received
    @Register(bitWidth: 32)
    struct EVENTS_RXDREADY {
        /// TWI RXD byte received
        @ReadWrite(bits: 0..<1, as: EVENTS_RXDREADY_FIELDValues.self)
        var events_rxdready_field: EVENTS_RXDREADY_FIELD
    }

    /// TWI TXD byte sent
    @Register(bitWidth: 32)
    struct EVENTS_TXDSENT {
        /// TWI TXD byte sent
        @ReadWrite(bits: 0..<1, as: EVENTS_TXDSENT_FIELDValues.self)
        var events_txdsent_field: EVENTS_TXDSENT_FIELD
    }

    /// TWI error
    @Register(bitWidth: 32)
    struct EVENTS_ERROR {
        /// TWI error
        @ReadWrite(bits: 0..<1, as: EVENTS_ERROR_FIELDValues.self)
        var events_error_field: EVENTS_ERROR_FIELD
    }

    /// TWI byte boundary, generated before each byte that is sent or received
    @Register(bitWidth: 32)
    struct EVENTS_BB {
        /// TWI byte boundary, generated before each byte that is sent or received
        @ReadWrite(bits: 0..<1, as: EVENTS_BB_FIELDValues.self)
        var events_bb_field: EVENTS_BB_FIELD
    }

    /// TWI entered the suspended state
    @Register(bitWidth: 32)
    struct EVENTS_SUSPENDED {
        /// TWI entered the suspended state
        @ReadWrite(bits: 0..<1, as: EVENTS_SUSPENDED_FIELDValues.self)
        var events_suspended_field: EVENTS_SUSPENDED_FIELD
    }

    /// Shortcuts between local events and tasks
    @Register(bitWidth: 32)
    struct SHORTS {
        /// Shortcut between event BB and task SUSPEND
        @ReadWrite(bits: 0..<1, as: BB_SUSPENDValues.self)
        var bb_suspend: BB_SUSPEND

        /// Shortcut between event BB and task STOP
        @ReadWrite(bits: 1..<2, as: BB_STOPValues.self)
        var bb_stop: BB_STOP
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event STOPPED
        @ReadWrite(bits: 1..<2)
        var stopped: STOPPED

        /// Write '1' to enable interrupt for event RXDREADY
        @ReadWrite(bits: 2..<3)
        var rxdready: RXDREADY

        /// Write '1' to enable interrupt for event TXDSENT
        @ReadWrite(bits: 7..<8)
        var txdsent: TXDSENT

        /// Write '1' to enable interrupt for event ERROR
        @ReadWrite(bits: 9..<10)
        var error: ERROR

        /// Write '1' to enable interrupt for event BB
        @ReadWrite(bits: 14..<15)
        var bb: BB

        /// Write '1' to enable interrupt for event SUSPENDED
        @ReadWrite(bits: 18..<19)
        var suspended: SUSPENDED
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event STOPPED
        @ReadWrite(bits: 1..<2)
        var stopped: STOPPED

        /// Write '1' to disable interrupt for event RXDREADY
        @ReadWrite(bits: 2..<3)
        var rxdready: RXDREADY

        /// Write '1' to disable interrupt for event TXDSENT
        @ReadWrite(bits: 7..<8)
        var txdsent: TXDSENT

        /// Write '1' to disable interrupt for event ERROR
        @ReadWrite(bits: 9..<10)
        var error: ERROR

        /// Write '1' to disable interrupt for event BB
        @ReadWrite(bits: 14..<15)
        var bb: BB

        /// Write '1' to disable interrupt for event SUSPENDED
        @ReadWrite(bits: 18..<19)
        var suspended: SUSPENDED
    }

    /// Error source
    @Register(bitWidth: 32)
    struct ERRORSRC {
        /// Overrun error
        @ReadWrite(bits: 0..<1)
        var overrun: OVERRUN

        /// NACK received after sending the address (write '1' to clear)
        @ReadWrite(bits: 1..<2)
        var anack: ANACK

        /// NACK received after sending a data byte (write '1' to clear)
        @ReadWrite(bits: 2..<3)
        var dnack: DNACK
    }

    /// Enable TWI
    @Register(bitWidth: 32)
    struct ENABLE {
        /// Enable or disable TWI
        @ReadWrite(bits: 0..<4, as: ENABLE_FIELDValues.self)
        var enable_field: ENABLE_FIELD
    }

    /// RXD register
    @Register(bitWidth: 32)
    struct RXD {
        /// RXD register
        @ReadOnly(bits: 0..<8)
        var rxd_field: RXD_FIELD
    }

    /// TXD register
    @Register(bitWidth: 32)
    struct TXD {
        /// TXD register
        @ReadWrite(bits: 0..<8)
        var txd_field: TXD_FIELD
    }

    /// TWI frequency. Accuracy depends on the HFCLK source selected.
    @Register(bitWidth: 32)
    struct FREQUENCY {
        /// TWI master clock frequency
        @ReadWrite(bits: 0..<32, as: FREQUENCY_FIELDValues.self)
        var frequency_field: FREQUENCY_FIELD
    }

    /// Address used in the TWI transfer
    @Register(bitWidth: 32)
    struct ADDRESS {
        /// Address used in the TWI transfer
        @ReadWrite(bits: 0..<7)
        var address_field: ADDRESS_FIELD
    }

    /// Unspecified
    @RegisterBlock
    struct PSEL {
        /// Pin select for SCL
        @RegisterBlock(offset: 0x0)
        var scl: Register<SCL>

        /// Pin select for SDA
        @RegisterBlock(offset: 0x4)
        var sda: Register<SDA>
    }
}

extension TWI0.PSEL {
    /// Pin select for SCL
    @Register(bitWidth: 32)
    struct SCL {
        /// Pin number
        @ReadWrite(bits: 0..<5)
        var pin: PIN

        /// Port number
        @ReadWrite(bits: 5..<6)
        var port: PORT

        /// Connection
        @ReadWrite(bits: 31..<32, as: CONNECTValues.self)
        var connect: CONNECT
    }

    /// Pin select for SDA
    @Register(bitWidth: 32)
    struct SDA {
        /// Pin number
        @ReadWrite(bits: 0..<5)
        var pin: PIN

        /// Port number
        @ReadWrite(bits: 5..<6)
        var port: PORT

        /// Connection
        @ReadWrite(bits: 31..<32, as: CONNECTValues.self)
        var connect: CONNECT
    }
}

extension TWI0.TASKS_STARTRX {
    struct TASKS_STARTRX_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.TASKS_STARTTX {
    struct TASKS_STARTTX_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.TASKS_STOP {
    struct TASKS_STOP_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.TASKS_SUSPEND {
    struct TASKS_SUSPEND_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.TASKS_RESUME {
    struct TASKS_RESUME_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.EVENTS_STOPPED {
    struct EVENTS_STOPPED_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.EVENTS_RXDREADY {
    struct EVENTS_RXDREADY_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.EVENTS_TXDSENT {
    struct EVENTS_TXDSENT_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.EVENTS_ERROR {
    struct EVENTS_ERROR_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.EVENTS_BB {
    struct EVENTS_BB_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.EVENTS_SUSPENDED {
    struct EVENTS_SUSPENDED_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.SHORTS {
    struct BB_SUSPENDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.SHORTS {
    struct BB_STOPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable shortcut
        static let Disabled = Self(rawValue: 0x0)

        /// Enable shortcut
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.ENABLE {
    struct ENABLE_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 4

        /// Disable TWI
        static let Disabled = Self(rawValue: 0x0)

        /// Enable TWI
        static let Enabled = Self(rawValue: 0x5)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.FREQUENCY {
    struct FREQUENCY_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 32

        /// 100 kbps
        static let K100 = Self(rawValue: 0x1980000)

        /// 250 kbps
        static let K250 = Self(rawValue: 0x4000000)

        /// 400 kbps (actual rate 410.256 kbps)
        static let K400 = Self(rawValue: 0x6680000)

        var rawValue: UInt32

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.PSEL.SCL {
    struct CONNECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disconnect
        static let Disconnected = Self(rawValue: 0x1)

        /// Connect
        static let Connected = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension TWI0.PSEL.SDA {
    struct CONNECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disconnect
        static let Disconnected = Self(rawValue: 0x1)

        /// Connect
        static let Connected = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
