// Generated by svd2swift.

import MMIO

/// User information configuration registers
@RegisterBlock
struct UICR {
    /// Description collection: Reserved for Nordic firmware design
    @RegisterBlock(offset: 0x14, stride: 0x4, count: 13)
    var nrffw: RegisterArray<NRFFW>

    /// Description collection: Reserved for Nordic hardware design
    @RegisterBlock(offset: 0x50, stride: 0x4, count: 12)
    var nrfhw: RegisterArray<NRFHW>

    /// Description collection: Reserved for customer
    @RegisterBlock(offset: 0x80, stride: 0x4, count: 32)
    var customer: RegisterArray<CUSTOMER>

    /// Description collection: Mapping of the nRESET function (see POWER chapter for details)
    @RegisterBlock(offset: 0x200, stride: 0x4, count: 2)
    var pselreset: RegisterArray<PSELRESET>

    /// Access port protection
    @RegisterBlock(offset: 0x208)
    var approtect: Register<APPROTECT>

    /// Setting of pins dedicated to NFC functionality: NFC antenna or GPIO
    @RegisterBlock(offset: 0x20c)
    var nfcpins: Register<NFCPINS>

    /// Processor debug control
    @RegisterBlock(offset: 0x210)
    var debugctrl: Register<DEBUGCTRL>

    /// Output voltage from REG0 regulator stage. The maximum output voltage from this stage is given as VDDH - V_VDDH-VDD.
    @RegisterBlock(offset: 0x304)
    var regout0: Register<REGOUT0>
}

extension UICR {
    /// Description collection: Reserved for Nordic firmware design
    @Register(bitWidth: 32)
    struct NRFFW {
        /// Reserved for Nordic firmware design
        @ReadWrite(bits: 0..<32)
        var nrffw_field: NRFFW_FIELD
    }

    /// Description collection: Reserved for Nordic hardware design
    @Register(bitWidth: 32)
    struct NRFHW {
        /// Reserved for Nordic hardware design
        @ReadWrite(bits: 0..<32)
        var nrfhw_field: NRFHW_FIELD
    }

    /// Description collection: Reserved for customer
    @Register(bitWidth: 32)
    struct CUSTOMER {
        /// Reserved for customer
        @ReadWrite(bits: 0..<32)
        var customer_field: CUSTOMER_FIELD
    }

    /// Description collection: Mapping of the nRESET function (see POWER chapter for details)
    @Register(bitWidth: 32)
    struct PSELRESET {
        /// GPIO pin number onto which nRESET is exposed
        @ReadWrite(bits: 0..<5)
        var pin: PIN

        /// Port number onto which nRESET is exposed
        @ReadWrite(bits: 5..<6)
        var port: PORT

        /// Connection
        @ReadWrite(bits: 31..<32, as: CONNECTValues.self)
        var connect: CONNECT
    }

    /// Access port protection
    @Register(bitWidth: 32)
    struct APPROTECT {
        /// Enable or disable access port protection.
        @ReadWrite(bits: 0..<8, as: PALLValues.self)
        var pall: PALL
    }

    /// Setting of pins dedicated to NFC functionality: NFC antenna or GPIO
    @Register(bitWidth: 32)
    struct NFCPINS {
        /// Setting of pins dedicated to NFC functionality
        @ReadWrite(bits: 0..<1, as: PROTECTValues.self)
        var protect: PROTECT
    }

    /// Processor debug control
    @Register(bitWidth: 32)
    struct DEBUGCTRL {
        /// Configure CPU non-intrusive debug features
        @ReadWrite(bits: 0..<8, as: CPUNIDENValues.self)
        var cpuniden: CPUNIDEN

        /// Configure CPU flash patch and breakpoint (FPB) unit behavior
        @ReadWrite(bits: 8..<16, as: CPUFPBENValues.self)
        var cpufpben: CPUFPBEN
    }

    /// Output voltage from REG0 regulator stage. The maximum output voltage from this stage is given as VDDH - V_VDDH-VDD.
    @Register(bitWidth: 32)
    struct REGOUT0 {
        /// Output voltage from REG0 regulator stage.
        @ReadWrite(bits: 0..<3, as: VOUTValues.self)
        var vout: VOUT
    }
}

extension UICR.PSELRESET {
    struct CONNECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disconnect
        static let Disconnected = Self(rawValue: 0x1)

        /// Connect
        static let Connected = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension UICR.APPROTECT {
    struct PALLValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 8

        /// Hardware disable of access port protection for devices where access port protection is controlled by hardware
        static let Disabled = Self(rawValue: 0xff)

        /// Hardware disable of access port protection for devices where access port protection is controlled by hardware and software
        static let HwDisabled = Self(rawValue: 0x5a)

        /// Enable
        static let Enabled = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension UICR.NFCPINS {
    struct PROTECTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Operation as GPIO pins. Same protection as normal GPIO pins.
        static let Disabled = Self(rawValue: 0x0)

        /// Operation as NFC antenna pins. Configures the protection for NFC operation.
        static let NFC = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension UICR.DEBUGCTRL {
    struct CPUNIDENValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 8

        /// Enable CPU ITM and ETM functionality (default behavior)
        static let Enabled = Self(rawValue: 0xff)

        /// Disable CPU ITM and ETM functionality
        static let Disabled = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension UICR.DEBUGCTRL {
    struct CPUFPBENValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 8

        /// Enable CPU FPB unit (default behavior)
        static let Enabled = Self(rawValue: 0xff)

        /// Disable CPU FPB unit. Writes into the FPB registers will be ignored.
        static let Disabled = Self(rawValue: 0x0)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension UICR.REGOUT0 {
    struct VOUTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 3

        /// 1.8 V
        static let _1V8 = Self(rawValue: 0x0)

        /// 2.1 V
        static let _2V1 = Self(rawValue: 0x1)

        /// 2.4 V
        static let _2V4 = Self(rawValue: 0x2)

        /// 2.7 V
        static let _2V7 = Self(rawValue: 0x3)

        /// 3.0 V
        static let _3V0 = Self(rawValue: 0x4)

        /// 3.3 V
        static let _3V3 = Self(rawValue: 0x5)

        /// Default voltage: 1.8 V
        static let DEFAULT = Self(rawValue: 0x7)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
