// Generated by svd2swift.

import MMIO

/// Watchdog Timer
@RegisterBlock
struct WDT {
    /// Start the watchdog
    @RegisterBlock(offset: 0x0)
    var tasks_start: Register<TASKS_START>

    /// Watchdog timeout
    @RegisterBlock(offset: 0x100)
    var events_timeout: Register<EVENTS_TIMEOUT>

    /// Enable interrupt
    @RegisterBlock(offset: 0x304)
    var intenset: Register<INTENSET>

    /// Disable interrupt
    @RegisterBlock(offset: 0x308)
    var intenclr: Register<INTENCLR>

    /// Run status
    @RegisterBlock(offset: 0x400)
    var runstatus: Register<RUNSTATUS>

    /// Request status
    @RegisterBlock(offset: 0x404)
    var reqstatus: Register<REQSTATUS>

    /// Counter reload value
    @RegisterBlock(offset: 0x504)
    var crv: Register<CRV>

    /// Enable register for reload request registers
    @RegisterBlock(offset: 0x508)
    var rren: Register<RREN>

    /// Configuration register
    @RegisterBlock(offset: 0x50c)
    var config: Register<CONFIG>

    /// Description collection: Reload request n
    @RegisterBlock(offset: 0x600, stride: 0x4, count: 8)
    var rr: RegisterArray<RR>
}

extension WDT {
    /// Start the watchdog
    @Register(bitWidth: 32)
    struct TASKS_START {
        /// Start the watchdog
        @WriteOnly(bits: 0..<1, as: TASKS_START_FIELDValues.self)
        var tasks_start_field: TASKS_START_FIELD
    }

    /// Watchdog timeout
    @Register(bitWidth: 32)
    struct EVENTS_TIMEOUT {
        /// Watchdog timeout
        @ReadWrite(bits: 0..<1, as: EVENTS_TIMEOUT_FIELDValues.self)
        var events_timeout_field: EVENTS_TIMEOUT_FIELD
    }

    /// Enable interrupt
    @Register(bitWidth: 32)
    struct INTENSET {
        /// Write '1' to enable interrupt for event TIMEOUT
        @ReadWrite(bits: 0..<1)
        var timeout: TIMEOUT
    }

    /// Disable interrupt
    @Register(bitWidth: 32)
    struct INTENCLR {
        /// Write '1' to disable interrupt for event TIMEOUT
        @ReadWrite(bits: 0..<1)
        var timeout: TIMEOUT
    }

    /// Run status
    @Register(bitWidth: 32)
    struct RUNSTATUS {
        /// Indicates whether or not the watchdog is running
        @ReadOnly(bits: 0..<1, as: RUNSTATUS_FIELDValues.self)
        var runstatus_field: RUNSTATUS_FIELD
    }

    /// Request status
    @Register(bitWidth: 32)
    struct REQSTATUS {
        /// Request status for RR[0] register
        @ReadOnly(bits: 0..<1, as: RR0Values.self)
        var rr0: RR0

        /// Request status for RR[1] register
        @ReadOnly(bits: 1..<2, as: RR1Values.self)
        var rr1: RR1

        /// Request status for RR[2] register
        @ReadOnly(bits: 2..<3, as: RR2Values.self)
        var rr2: RR2

        /// Request status for RR[3] register
        @ReadOnly(bits: 3..<4, as: RR3Values.self)
        var rr3: RR3

        /// Request status for RR[4] register
        @ReadOnly(bits: 4..<5, as: RR4Values.self)
        var rr4: RR4

        /// Request status for RR[5] register
        @ReadOnly(bits: 5..<6, as: RR5Values.self)
        var rr5: RR5

        /// Request status for RR[6] register
        @ReadOnly(bits: 6..<7, as: RR6Values.self)
        var rr6: RR6

        /// Request status for RR[7] register
        @ReadOnly(bits: 7..<8, as: RR7Values.self)
        var rr7: RR7
    }

    /// Counter reload value
    @Register(bitWidth: 32)
    struct CRV {
        /// Counter reload value in number of cycles of the 32.768 kHz clock
        @ReadWrite(bits: 0..<32)
        var crv_field: CRV_FIELD
    }

    /// Enable register for reload request registers
    @Register(bitWidth: 32)
    struct RREN {
        /// Enable or disable RR[0] register
        @ReadWrite(bits: 0..<1, as: RR0Values.self)
        var rr0: RR0

        /// Enable or disable RR[1] register
        @ReadWrite(bits: 1..<2, as: RR1Values.self)
        var rr1: RR1

        /// Enable or disable RR[2] register
        @ReadWrite(bits: 2..<3, as: RR2Values.self)
        var rr2: RR2

        /// Enable or disable RR[3] register
        @ReadWrite(bits: 3..<4, as: RR3Values.self)
        var rr3: RR3

        /// Enable or disable RR[4] register
        @ReadWrite(bits: 4..<5, as: RR4Values.self)
        var rr4: RR4

        /// Enable or disable RR[5] register
        @ReadWrite(bits: 5..<6, as: RR5Values.self)
        var rr5: RR5

        /// Enable or disable RR[6] register
        @ReadWrite(bits: 6..<7, as: RR6Values.self)
        var rr6: RR6

        /// Enable or disable RR[7] register
        @ReadWrite(bits: 7..<8, as: RR7Values.self)
        var rr7: RR7
    }

    /// Configuration register
    @Register(bitWidth: 32)
    struct CONFIG {
        /// Configure the watchdog to either be paused, or kept running, while the CPU is sleeping
        @ReadWrite(bits: 0..<1, as: SLEEPValues.self)
        var sleep: SLEEP

        /// Configure the watchdog to either be paused, or kept running, while the CPU is halted by the debugger
        @ReadWrite(bits: 3..<4, as: HALTValues.self)
        var halt: HALT
    }

    /// Description collection: Reload request n
    @Register(bitWidth: 32)
    struct RR {
        /// Reload request register
        @WriteOnly(bits: 0..<32, as: RR_FIELDValues.self)
        var rr_field: RR_FIELD
    }
}

extension WDT.TASKS_START {
    struct TASKS_START_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Trigger task
        static let Trigger = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.EVENTS_TIMEOUT {
    struct EVENTS_TIMEOUT_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Event not generated
        static let NotGenerated = Self(rawValue: 0x0)

        /// Event generated
        static let Generated = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RUNSTATUS {
    struct RUNSTATUS_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Watchdog not running
        static let NotRunning = Self(rawValue: 0x0)

        /// Watchdog is running
        static let Running = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[0] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[0] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[1] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[1] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[2] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[2] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[3] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[3] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR4Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[4] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[4] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR5Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[5] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[5] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR6Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[6] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[6] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.REQSTATUS {
    struct RR7Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// RR[7] register is not enabled, or are already requesting reload
        static let DisabledOrRequested = Self(rawValue: 0x0)

        /// RR[7] register is enabled, and are not yet requesting reload
        static let EnabledAndUnrequested = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR0Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[0] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[0] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR1Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[1] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[1] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR2Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[2] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[2] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR3Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[3] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[3] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR4Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[4] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[4] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR5Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[5] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[5] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR6Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[6] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[6] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RREN {
    struct RR7Values: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Disable RR[7] register
        static let Disabled = Self(rawValue: 0x0)

        /// Enable RR[7] register
        static let Enabled = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.CONFIG {
    struct SLEEPValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Pause watchdog while the CPU is sleeping
        static let Pause = Self(rawValue: 0x0)

        /// Keep the watchdog running while the CPU is sleeping
        static let Run = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.CONFIG {
    struct HALTValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 1

        /// Pause watchdog while the CPU is halted by the debugger
        static let Pause = Self(rawValue: 0x0)

        /// Keep the watchdog running while the CPU is halted by the debugger
        static let Run = Self(rawValue: 0x1)

        var rawValue: UInt8

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}

extension WDT.RR {
    struct RR_FIELDValues: BitFieldProjectable, RawRepresentable {
        static let bitWidth = 32

        /// Value to request a reload of the watchdog timer
        static let Reload = Self(rawValue: 0x6e524635)

        var rawValue: UInt32

        @inlinable @inline(__always)
        init(rawValue: Self.RawValue) {
            self.rawValue = rawValue
        }
    }
}
